In [18]:
from estnltk import Text
from estnltk.taggers import VabamorfTagger, VabamorfAnalyzer
from estnltk_neural.taggers import StanzaSyntaxTagger
from estnltk.converters import text_to_json, json_to_text
import sys, os
import re
import csv
import pandas as pd
import json
from tqdm import tqdm
import estnltk

In [6]:
pd.set_option('display.max_colwidth', None)
pd.set_option("display.show_dimensions", True)

In [54]:
BM_DIR = "../../locative_adverbial/benchmarks/morph_syntax_errors/"

YHILDUMINE_DIR = BM_DIR + "yhildumine/" 
YHILDUMINE = YHILDUMINE_DIR + "gpt_10K_b10_run01_no_yhildumine.csv"

VKESKSONA_DIR = BM_DIR + "v_kesksona/" 
VKESKSONA = VKESKSONA_DIR + "gpt_10K_b10_run01_vkesksona.csv"

NUM_DIR = BM_DIR + "numbers_with_case/" 
NUMBERS = NUM_DIR + "gpt_10k_b10_run01_no_numbers_w_case.csv"

MORPH_DIR = BM_DIR + "morphology_errors/" 
MORPH = MORPH_DIR + "gpt_10k_b10_run01_morph_syntax_errors.csv"

In [3]:
morf_tagger = VabamorfAnalyzer(output_layer='morph_analysis')
stanza_tagger = StanzaSyntaxTagger(input_type='morph_extended', input_morph_layer='morph_extended')

Downloading resources index: 23.4kB [00:00, 13.4MB/s]

## Ühildumine

In [4]:
df = pd.read_csv(YHILDUMINE, sep=",", encoding="utf-8")

In [16]:
texts_list = []

for i in range(len(df)):
    ex = df.iloc[[i]]
    
    txt = Text(ex.iloc[0]["sentence"])
    txt.tag_layer("words")
    txt.tag_layer("sentences")
    morf_tagger.tag(txt)
    txt.tag_layer('morph_extended')
    stanza_tagger.tag( txt )
    
    meta = {"sentence_id":int(ex.iloc[0]["sentence_id"]) , "head_id":int(ex.iloc[0]["head_id"]) , 
            "head_loc": int(ex.iloc[0]["head_loc"]), "verb": ex.iloc[0]["verb"], 
            "verb_compound": ex.iloc[0]["verb_compound"], "morph_case": ex.iloc[0]["morph_case"],
           "form": ex.iloc[0]["form"], "lemma": ex.iloc[0]["lemma"]}
    
    txt.meta = meta
    
    texts_list.append(txt)

In [17]:
for i, txt in enumerate(texts_list):
    text_to_json(txt, file=f"{YHILDUMINE_DIR}/text_{i}.json")

## V-kesksõna

In [22]:
df = pd.read_csv(VKESKSONA, sep=",", encoding="utf-8")

In [23]:
texts_list = []

for i in range(len(df)):
    ex = df.iloc[[i]]
    
    txt = Text(ex.iloc[0]["sentence"])
    txt.tag_layer("words")
    txt.tag_layer("sentences")
    morf_tagger.tag(txt)
    txt.tag_layer('morph_extended')
    stanza_tagger.tag( txt )
    
    meta = {"sentence_id":int(ex.iloc[0]["sentence_id"]) , "head_id":int(ex.iloc[0]["head_id"]) , 
            "head_loc": int(ex.iloc[0]["head_loc"]), "verb": ex.iloc[0]["verb"], 
            "verb_compound": ex.iloc[0]["verb_compound"], "morph_case": ex.iloc[0]["morph_case"],
           "form": ex.iloc[0]["form"], "lemma": ex.iloc[0]["lemma"]}
    
    txt.meta = meta
    
    texts_list.append(txt)

In [24]:
for i, txt in enumerate(texts_list):
    text_to_json(txt, file=f"{VKESKSONA_DIR}/text_{i}.json")

## Numbers with case

In [27]:
df = pd.read_csv(NUMBERS, sep=",", encoding="utf-8")

In [28]:
texts_list = []

for i in range(len(df)):
    ex = df.iloc[[i]]
    
    txt = Text(ex.iloc[0]["sentence"])
    txt.tag_layer("words")
    txt.tag_layer("sentences")
    morf_tagger.tag(txt)
    txt.tag_layer('morph_extended')
    stanza_tagger.tag( txt )
    
    meta = {"sentence_id":int(ex.iloc[0]["sentence_id"]) , "head_id":int(ex.iloc[0]["head_id"]) , 
            "head_loc": int(ex.iloc[0]["head_loc"]), "verb": ex.iloc[0]["verb"], 
            "verb_compound": ex.iloc[0]["verb_compound"], "morph_case": ex.iloc[0]["morph_case"],
           "form": ex.iloc[0]["form"], "lemma": ex.iloc[0]["lemma"]}
    
    txt.meta = meta
    
    texts_list.append(txt)

In [29]:
for i, txt in enumerate(texts_list):
    text_to_json(txt, file=f"{NUM_DIR}/text_{i}.json")

## Morph errors

In [57]:
df = pd.read_csv(MORPH, sep=",", encoding="utf-8")

In [58]:
texts_list = []

for i in range(len(df)):
    ex = df.iloc[[i]]
    
    txt = Text(ex.iloc[0]["sentence"])
    txt.tag_layer("words")
    txt.tag_layer("sentences")
    morf_tagger.tag(txt)
    txt.tag_layer('morph_extended')
    stanza_tagger.tag( txt )
    
    meta = {"sentence_id":int(ex.iloc[0]["sentence_id"]) , "head_id":int(ex.iloc[0]["head_id"]) , 
            "head_loc": int(ex.iloc[0]["head_loc"]), "verb": ex.iloc[0]["verb"], 
            "verb_compound": ex.iloc[0]["verb_compound"], "morph_case": ex.iloc[0]["morph_case"],
           "form": ex.iloc[0]["form"], "lemma": ex.iloc[0]["lemma"]}
    
    txt.meta = meta
    
    texts_list.append(txt)

In [59]:
for i, txt in enumerate(texts_list):
    text_to_json(txt, file=f"{MORPH_DIR}/text_{i}.json")

### kontroll: sisselugemine

In [61]:
f = "../../locative_adverbial/benchmarks/morph_syntax_errors/yhildumine/text_13.json"
f = "../../locative_adverbial/benchmarks/morph_syntax_errors/v_kesksona/text_1.json"
f = "../../locative_adverbial/benchmarks/morph_syntax_errors/numbers_with_case/text_15.json"
f = "../../locative_adverbial/benchmarks/morph_syntax_errors/morphology_errors/text_11.json"

text_import = json_to_text(file=f)
text_import#.morph_analysis

Text(text='" Käesoleval aastal on viis protsenti praktiseerivatest arstidest oma dokumendid välja võtnud , et välismaal tööle asuda , " sõnas Kork .')

## Morpholgy_errors readme näited csv-sse

In [48]:
examples = """

vanuses + töötama: Sellegipoolest töötasid eelmisel aastal kokku 659 Tallinna noort vanuses 13-18 aastat 34 linnasiseses ja üheksas linnavälises rühmas .

räägi + ronima: staff: kassnaine krt roni privasse räägi oma murest siis

kahekuulist + rändama: Septembri algul rändas viis last pärast kahekuulist eri peredes veedetud suve lastekodusse .

laiustesse + mahtuma: Seattleis tuli kohaliku praamiliini laevadel istekohad välja vahetada pärast reisijate kaebusi , et nad ei mahu 45 sentimeetri laiustesse toolidesse ära .

haigetel + paiknema: Sellele võib lihtsalt vastata , väites , et need , kelle raamatutest ning ideedest oli äsja juttu , paiknevad Lääne pühiskonna psüühiliselt haigetel äärealadel .

25 000-sse + jõudma: STV pakutavad kanalid jõuavad 25 000-sse koju .

igal + lamama: Üks pealtnägija rääkis BBCle , et nägi , kuidas kahekordne buss oli lõhki nagu " karp sardiine " ning inimesi lamas igal pool .

15sse + saama: Maaliit sai 15sse ja Isamaaliit 14sse volikokku .

barokkstiilis + protesteerima: Kui aga Rosen 1760ndatel aastatel selle kõrvale oma maja ( praegu Rootsi saatkond ) ehitas , siis protesteerisid selle barokkstiilis ehitise vastu just Mustpeade vennaskonna liikmed : pikuti tänava poole olev maja oli neile vastuvõetamatu , sest teised majad asusid ju otsapidi tänava poole .

leedulasest + röövima: 61-aastaselt leedulasest bussijuhilt elu röövinud õnnetus toimus Eurolines Eesti juhi Hugo Osula sõnul eile kella kahe ajal pärastlõunal kohaliku aja järgi Salacgriva asula läheduses , 14-15 kilomeetri kaugusel Eesti piirist .

neljapäeval + lamama: Tartus viis kiirabi neljapäeval ülikooli kliinikumi erakorralise meditsiini osakonda kontaktivõimetuna maas lamanud üliraskes joobes tüdruku .

arstidest + võtma: " Käesoleval aastal on viis protsenti praktiseerivatest arstidest oma dokumendid välja võtnud , et välismaal tööle asuda , " sõnas Kork .

kriisis + laskma: Küsimus , miks politseinikud psüühilises kriisis enesetapjat enne autosse tungimist maha ei lasknud , on küsimus , mida internetikommentaarides on esitatud korduvalt .

ühenduses + eksponeerima: Jakovlev eksponeerib Sambas sõbralikus ühenduses lampe , toole ja õlimaale .

keeltesse + toimuma: 18.-22. maini toimus Käsmu loomemajas eesti kirjanduse muu-desse keeltesse tõlkijate seminar .

paremuselt + sõitma: Korsika ralli avapäeva eelviimasel , 17,72 km pikkusel neljandal kiiruskatsel sõitis Markko Märtin ( Ford ) välja paremuselt üheksanda aja ja on samal kohal ka kokkuvõttes .

lobjakaselt + sõitma: Tartu-Tallinna maantee 25. kilomeetril sõitis naisjuht Ford Scorpioga lobjakaselt teelt välja ja paiskus üle katuse .

virtuaalsetes + koolitama: Häkkerid koolitavad niiöelda virtuaalsetes « treeninglaagrites » kasutajaid ja müüvad siis neid .

suvalisse + vedama: Samuti tundub üsna vähe tõenäoline , et korealased vedasid tohutuid koguseid TNT-sid suvalisse kohta , et maailma lollitada .

kaitseliitlasest + varastama: Poolesajal kaitseliitlasel , politseinikul ja päästeametnikul ei õnnestunud läinud nädala lõpuks leida Jõhvi lähedastest metsadest 23-aastast neiut , kes varastas kasuõe kaitseliitlasest mehelt püstoli ja lubas end tappa .

nimetusse + viskama: Vanim poeg Sulev viskas kivi kaugele-kaugele mingisse nimetusse järve .

igastahes + jooma: Siinsete kommenteerijate eilseid kogemusi silmas pidades ma igastahes töölaua taga täna kohvi ei joo

laiuselt + kulgema: Lava hõlmab kogu laulukaare ala muruesise asfaldini ning kulgeb laiuselt tuletornist raadiotornini .

jalas + magama: Vahepeal magasin , villased sokid jalas , sest kogu aeg tundus , et toas on külm .
"""

exes = [ex.strip() for ex in examples.split("\n") if ex.strip()!=""]

In [36]:
gpt_v03 = "../../results/n80_examples_large_v01/gpt_v03/gpt_10K_b10_run01.csv"
df1 = pd.read_csv(gpt_v03, sep=",", encoding="utf-8")

In [50]:
new_df = pd.DataFrame(columns=df.columns)

for ex in exes:
    parts = ex.split(":", 1)
    if len(parts) != 2:
        print(f"probleem: {ex}", parts)
    else:
        part2 = parts[0].split("+")
        form = part2[0].strip()
        verb = part2[1].strip()
        sent = parts[1].strip()
        
        row = df1[(df1["sentence"]==sent) & (df1["verb"]==verb) & (df1["form"]==form)]
        if len(row) != 1:
            print(ex, row)
        else:
            new_df = pd.concat([new_df, row])

In [51]:
new_df

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,classification,explanation,classification2,explanation2,timex_tag,ekilex_tag,ner_tag,is_time,is_alive,is_abstract,classification3
3241,2553763,4096876,9,töötama,kokku,in,vanus,vanuses,Sellegipoolest töötasid eelmisel aastal kokku 659 Tallinna noort vanuses 13-18 aastat 34 linnasiseses ja üheksas linnavälises rühmas .,no,"The phrase 'vanuses' relates to ages and not a location, so it is classified as not a location.",no,"The phrase 'vanuses' refers to age and not a location, so it is not classified as adverbial of place.",NaN,time,NaN,no,no,no,no
3825,19902437,29342838,7,ronima,NaN,ill,rääkima,räägi,staff: kassnaine krt roni privasse räägi oma murest siis,no,"'räägi' is not classified as a location because it is a verb meaning 'talk' or 'speak,' not a geographic entity.",no,"The phrase 'räägi' is a verb and does not indicate a place, thus it is not adverbial of place.",NaN,NaN,NaN,no,yes,no,yes
9331,15653540,24425127,7,rändama,NaN,el,kahekuul,kahekuulist,Septembri algul rändas viis last pärast kahekuulist eri peredes veedetud suve lastekodusse .,no,"The word 'kahekuulist' refers to a duration of time, not a specific location, so it is classified as 'no'.",no,The phrase 'kahekuulist' (two-month) is not an adverbial of place because it describes the duration of time and not a location.,NaN,NaN,NaN,no,no,no,no
4652,1241336,1973259,19,mahtuma,ära,ill,laius,laiustesse,"Seattleis tuli kohaliku praamiliini laevadel istekohad välja vahetada pärast reisijate kaebusi , et nad ei mahu 45 sentimeetri laiustesse toolidesse ära .",no,"The phrase 'laiustesse' was classified as not a location because it describes a measurement, not a geographic location.",no,"The phrase 'laiustesse' indicates dimensions or measurement and not a specific location, hence it is not adverbial of place.",NaN,NaN,NaN,no,no,no,no
8577,358889,555825,23,paiknema,NaN,ad,haige,haigetel,"Sellele võib lihtsalt vastata , väites , et need , kelle raamatutest ning ideedest oli äsja juttu , paiknevad Lääne pühiskonna psüühiliselt haigetel äärealadel .",no,"The phrase 'haigetel' refers to a condition or state of people, not a geographical or physical location.",no,"The term 'haigetel' refers to people (psychically ill individuals) rather than a place, thus it is not classified as an adverbial of place.",NaN,NaN,NaN,no,no,no,no
3840,16543867,25512645,5,jõudma,NaN,ill,25000,25 000-sse,STV pakutavad kanalid jõuavad 25 000-sse koju .,no,"The phrase '25 000-sse' indicates a quantity rather than a specific geographic location, so it is classified as 'no'.",no,"The phrase '25 000-sse' refers to the number of homes and indicates a quantity rather than a specific location, so it is not classified as an adverbial of place.",NaN,NaN,NaN,no,no,yes,yes
8557,6202404,9960704,22,lamama,NaN,ad,iga,igal,"Üks pealtnägija rääkis BBCle , et nägi , kuidas kahekordne buss oli lõhki nagu "" karp sardiine "" ning inimesi lamas igal pool .",no,"The word 'igal' conveys quantity and dispersion, not a specific physical place, so it is classified as 'no'.",no,"The phrase 'igal' refers to distribution or extent across all locations, but it does not specify a single place, so it is not classified as an adverbial of place.",NaN,NaN,NaN,no,no,no,no
1058,7836422,12557268,3,saama,NaN,ill,15,15sse,Maaliit sai 15sse ja Isamaaliit 14sse volikokku .,no,"The phrase '15sse' represents a numerical or positional reference rather than a location, so it was classified as 'no'.",no,"The phrase '15sse' indicates a numerical position or ranking rather than a location, so it is not an adverbial of place.",NaN,NaN,NaN,no,no,no,no
6158,10074222,16160298,20,protesteerima,NaN,in,barokkstiil,barokkstiilis,"Kui aga Rosen 1760ndatel aastatel selle kõrvale oma maja ( praegu Rootsi saatkond ) ehitas , siis protesteerisid selle barokkstiilis ehitise vastu just Mustpeade vennaskonna liikmed : pikuti tänava poole olev maja oli neile vastuvõetamatu , sest teised majad asusid ju otsapidi tänava poole .",no,The phrase 'barokkstiilis' refers to a style (Baroque) and not a physical location.,no,"The phrase 'barokkstiilis' describes the architectural style and not a location, so it is not an adverbial of place.",NaN,NaN,NaN,no,no,no,no
9063,821266,1310149,2,röövima,NaN,el,leedulane,leedulasest,"61-aastaselt leedulasest bussijuhilt elu röövinud õnnetus toimus Eurolines Eesti juhi Hugo Osula sõnul eile kella kahe ajal pärastlõunal kohaliku aja järgi Salacgriva asula läheduses , 14-15 kilomeetri kaugusel Eesti piirist .",no,"The phrase 'leedulasest' refers to a person of Lithuanian origin, not a location.",no,"The phrase 'leedulasest' refers to the nationality of the bus driver, not to a specific location, so it is not classified as an adverbial of place.",NaN,alive,NaN,no,yes,no,yes
3312,13011236,20817691,4,lamama,NaN,ad,neljapäev,neljapäeval,Tartus viis kiirabi neljapäeval ülikooli kliinikumi erakorralise meditsiini osakonda kontaktivõimetuna maas lamanud üliraskes joobes tüdruku .,no,"The word 'neljapäeval' refers to a time (Thursday), not a physical location.",no,"It was classified as 'no' because 'neljapäeval' refers to time rather than a location, making it an adverbial of time, not place.",NaN,time,NaN,yes,no,no,no
2752,2920987,4682504,8,võtma,välja,el,arst,arstidest,""" Käesoleval aastal on viis protsenti praktiseerivatest arstidest oma dokumendid välja võtnud , et välismaal tööle asuda , "" sõnas Kork .",no,The term 'arstidest' refers to a profession and not a specific location.,no,The phrase 'arstidest' is not an adverbial of place as it specifies a group (practicing doctors) rather than indicating a location.,NaN,alive,NaN,no,yes,no,yes
514,3210498,5156912,6,laskma,maha,in,kriis,kriisis,"Küsimus , miks politseinikud psüühilises kriisis enesetapjat enne autosse tungimist maha ei lasknud , on küsimus , mida internetikommentaarides on esitatud korduvalt .",no,The phrase 'kriisis' refers to a crisis or condition and does not specify a location.,no,"The phrase 'kriisis' describes a mental state (being in a crisis) rather than a location, so it is not an adverbial of place.",NaN,NaN,NaN,no,no,no,no
5478,10780331,17268871,5,eksponeerima,NaN,in,ühendus,ühenduses,"Jakovlev eksponeerib Sambas sõbralikus ühenduses lampe , toole ja õlimaale .",no,"The word 'ühenduses' implies being in connection or association, not a geographical or physical location.",no,"The word 'ühenduses' refers to a state or association rather than a specific location, so it is not an adverbial of place.",NaN,NaN,NaN,no,no,yes,yes
9421,5870970,9423223,11,toimuma,NaN,ill,keel,keeltesse,18.-22. maini toimus Käsmu loomemajas eesti kirjanduse muu-desse keeltesse tõlkijate seminar .,no,"'keeltesse' was classified as 'no' because it refers to languages, not a specific geographic location.",no,"The phrase 'keeltesse' indicates languages but does not describe a specific location, so it was not classified as an adverbial of place ('no').",NaN,NaN,NaN,no,no,no,no
8273,2537443,4070816,18,sõitma,välja,abl,paremus,paremuselt,"Korsika ralli avapäeva eelviimasel , 17,72 km pikkusel neljandal kiiruskatsel sõitis Markko Märtin ( Ford ) välja paremuselt üheksanda aja ja on samal kohal ka kokkuvõttes .",no,"The phrase 'paremuselt' refers to a ranking or comparison of performance, not a physical or geographical location, so it was classified as 'no'.",no,"The phrase 'paremuselt' indicates a ranking or position, not a place, so it is not adverbial of place.",NaN,NaN,NaN,no,no,no,no
8701,9748539,15641549,9,sõitma,välja,abl,lobjakane,lobjakaselt,Tartu-Tallinna maantee 25. kilomeetril sõitis naisjuht Ford Scorpioga lobjakaselt teelt välja ja paiskus üle katuse .,no,The phrase 'lobjakaselt' was classified as not location ('no') because it refers to a condition of the road (slushy) rather than a specific place.,no,"The phrase 'lobjakaselt' describes the condition of the road surface, which is manner-related rather than indicating a physical place, so it is not an adverbial of place.",NaN,NaN,NaN,no,no,no,no
5777,15519205,24236968,4,koolitama,NaN,in,virtuaalne,virtuaalsetes,Häkkerid koolitavad niiöelda virtuaalsetes « treeninglaagrites » kasutajaid ja müüvad siis neid .,no,"The phrase 'virtuaalsetes' refers to virtual environments, which are not physical locations.",no,"The phrase 'virtuaalsetes' describes the nature of the 'treeninglaagrites' (training camps) and not the location of an action, hence it is not adverbial of place.",NaN,NaN,NaN,no,no,yes,yes
9050,15517061,24233261,13,vedama,NaN,adit,suvaline,suvalisse,"Samuti tundub üsna vähe tõenäoline , et korealased vedasid tohutuid koguseid TNT-sid suvalisse kohta , et maailma lollitada .",no,"The phrase 'suvalisse' means 'random' or 'anywhere', and does not specify a definitive location, hence classified as 'no'.",no,The phrase 'suvalisse' was classified as not an adverbial of place because it does not denote a specific or clear location but rather an indefinite or random place.,NaN,NaN,NaN,no,no,no,no
630,10839515,17359659,22,varastama,NaN,el,kaitseliitlane,kaitseliitlasest,"Poolesajal kaitseliitlasel , politseinikul ja päästeametnikul ei õnnestunud läinud nädala lõpuks leida Jõhvi lähedastest metsadest 23-aastast neiut , kes varastas kasuõe kaitseliitlasest mehelt püstoli ja lubas end tappa .",no,"The term 'kaitseliitlasest' refers to a person (a defense league member) and not a place, so it is not classified as a location.",no,"The phrase 'kaitseliitlasest' describes a person or their identity, not a location, so it is not an adverbial of place.",NaN,alive,NaN,no,yes,no,yes
3133,11265806,18054916,8,viskama,NaN,adit,nimetus,nimetusse,Vanim poeg Sulev viskas kivi kaugele-kaugele mingisse nimetusse järve .,no,"The word 'nimetusse' describes the quality or characteristic of the lake being unnamed and not a specific geographical location, so it is classified as 'no'.",no,The phrase 'nimetusse' was classified as 'no' because it describes a characteristic (nameless) of the object 'järve' rather than specifying a place.,NaN,NaN,NaN,no,no,no,no
3618,18375128,27856796,8,jooma,NaN,in,igastahe,igastahes,Siinsete kommenteerijate eilseid kogemusi silmas pidades ma igastahes töölaua taga täna kohvi ei joo,no,"The phrase 'igastahes' is an adverb and not indicative of a location, so it was classified as 'no'.",no,"The phrase 'igastahes' is not an adverbial of place because it is an adverb expressing attitude, not a location.",NaN,NaN,NaN,no,no,no,no
902,1842677,2933676,10,kulgema,NaN,abl,laius,laiuselt,Lava hõlmab kogu laulukaare ala muruesise asfaldini ning kulgeb laiuselt tuletornist raadiotornini .,no,"The phrase 'laiuselt' indicates a dimension or extent, not a geographical location, so it was classified as 'no'.",no,The phrase 'laiuselt' is not classified as an adverbial of place because it describes a measurement or extent rather than a specific location.,NaN,NaN,NaN,no,no,no,no
7704,7956587,12752907,6,magama,NaN,in,jalg,jalas,"Vahepeal magasin , villased sokid jalas , sest kogu aeg tundus , et toas on külm .",no,"The word 'jalas' refers to something being on feet and not a geographical physical location, so it was classified as 'no'.",no,"The phrase 'jalas' is not classified as an adverbial of place because it specifies the location of the socks on the body, not an actual spatial location.",NaN,NaN,NaN,no,no,no,no

In [55]:
new_df.to_csv(MORPH, encoding="utf-8", index=False, sep=",", quoting=csv.QUOTE_MINIMAL)