In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

sys.path.append("..")

import csv
from collections import Counter

from methods.pattern_matching import *
from methods.helper_methods import *

### I Reading pre-filtered Estonian Reference Corpus sentences

In [3]:
INPUT_DIR = "../data/koondkorpus_sentences/el_conx_sentences_cleaned/"

In [4]:
data = read_texts_from_json(INPUT_DIR)

In [5]:
len(data)

89719

In [6]:
# EstNLTK Text-object of a sentence and it's annotation layers
data[0]

Text(text='Mis selle pronksist kujuga ikka juhtuda sai . . . ”')

In [7]:
# stanza syntax layer
data[0].v172_stanza_syntax

Layer(name='v172_stanza_syntax', attributes=('id', 'lemma', 'upostag', 'xpostag', 'feats', 'head', 'deprel', 'deps', 'misc', 'parent_span', 'children'), spans=SL[Span('Mis', [{'id': 1, 'lemma': 'mis', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'nom': 'nom'}, 'head': 6, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('selle', [{'id': 2, 'lemma': 'see', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'gen': 'gen'}, 'head': 3, 'deprel': 'det', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('pronksist', [{'id': 3, 'lemma': 'pronks', 'upostag': 'S', 'xpostag': 'S', 'feats': {'el': 'el', 'sg': 'sg', 'com': 'com'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('kujuga', [{'id': 4, 'lemma': 'kuju', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'kom': 'kom'}, 'head': 6, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('ikka', [{'id': 5, 'lemma': 'ikka', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 6, 'deprel': 'advmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('juhtuda', [{'id': 6, 'lemma': 'juhtuma', 'upostag': 'V', 'xpostag': 'V', 'feats': {'inf': 'inf', 'mod': 'mod'}, 'head': 0, 'deprel': 'root', 'deps': '_', 'misc': '_', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('sai', [{'id': 7, 'lemma': 'saama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'ps3': 'ps3', 'impf': 'impf', 'main': 'main', 'indic': 'indic'}, 'head': 6, 'deprel': 'aux', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 8, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 9, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 10, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('”', [{'id': 11, 'lemma': '”', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

In [8]:
# morphological analysis layer
data[0].morph_analysis

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Mis', [{'normalized_text': 'Mis', 'lemma': 'mis', 'root': 'mis', 'root_tokens': ['mis'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'P'}, {'normalized_text': 'Mis', 'lemma': 'mis', 'root': 'mis', 'root_tokens': ['mis'], 'ending': '0', 'clitic': '', 'form': 'pl n', 'partofspeech': 'P'}]),
Span('selle', [{'normalized_text': 'selle', 'lemma': 'see', 'root': 'see', 'root_tokens': ['see'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'P'}]),
Span('pronksist', [{'normalized_text': 'pronksist', 'lemma': 'pronks', 'root': 'pronks', 'root_tokens': ['pronks'], 'ending': 'st', 'clitic': '', 'form': 'sg el', 'partofspeech': 'S'}]),
Span('kujuga', [{'normalized_text': 'kujuga', 'lemma': 'kuju', 'root': 'kuju', 'root_tokens': ['kuju'], 'ending': 'ga', 'clitic': '', 'form': 'sg kom', 'partofspeech': 'S'}]),
Span('ikka', [{'normalized_text': 'ikka', 'lemma': 'ikka', 'root': 'ikka', 'root_tokens': ['ikka'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('juhtuda', [{'normalized_text': 'juhtuda', 'lemma': 'juhtuma', 'root': 'juhtu', 'root_tokens': ['juhtu'], 'ending': 'da', 'clitic': '', 'form': 'da', 'partofspeech': 'V'}]),
Span('sai', [{'normalized_text': 'sai', 'lemma': 'saama', 'root': 'saa', 'root_tokens': ['saa'], 'ending': 'i', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('”', [{'normalized_text': '”', 'lemma': '”', 'root': '”', 'root_tokens': ['”'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

### II Extracting elative construction pattern matches

In [9]:
# pattern of elative construction
el_conx_pattern = {
        "nodes": {
            "A": {
                "deprels": ["nmod"], # A has to be a substantive and a nominal modifier in singular elative case
                "partofspeeches": ["S"],
                "forms": ["sg el"],
                "lemmas": None,
                "lemma_regex": None,
                "instances": None
                },
            "B": {
                "deprels": None,
                "partofspeeches": ["S"], # B has to be a substantive
                "forms": None,
                "lemmas": None,
                "lemma_regex": None,
                "instances": None
                }
        },
        "node_restrictions": {
            "A": None,
            "B": {"deprels": ["nmod"], # B can't be a nominal modifier, in terminative case, nor can it's lemma end with "mine"-clitic
                  "partofspeeches": None,
                  "forms": ["sg ter", "pl ter"],
                  "lemmas": None,
                  "lemma_regex": [r".*mine$"],
                  "instances": None,
                  "parent": None,
                  "child": None
                }
        },
        "edges": [
            ("B", "A")  # B is head of A
        ],
        "order": [
            ("A", "BEFORE", "B") # A has to appear before B in text
        ]
    }

In [10]:
# finding elative construction instances from sentences based on pattern
match_sentences = []
matches = []

for idx, sentence in enumerate(data):

    sent_matches = get_pattern(stanza_words = sentence.v172_stanza_syntax, 
                                        pattern = el_conx_pattern, 
                                        anchor_name = "B")
    if len(sent_matches) > 0:
        match_sentences.append(sentence.v172_stanza_syntax)
        matches.append(sent_matches)

In [11]:
print(matches[0])

[{'B': Span('kujuga', [{'id': 4, 'lemma': 'kuju', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'kom': 'kom'}, 'head': 6, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]), 'A': Span('pronksist', [{'id': 3, 'lemma': 'pronks', 'upostag': 'S', 'xpostag': 'S', 'feats': {'el': 'el', 'sg': 'sg', 'com': 'com'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}])}]

In [12]:
# number of sentences in which elative construction occurs
print(len(match_sentences))

89605

In [13]:
# total number of elative construction matches found
n_matches = 0

for sent_matches_list in matches:
    n_matches+=len(sent_matches_list)

print(n_matches)

91784

In [14]:
# number of sentences in which elative construction occurs more than once
n_multiple_matches = 0

for sent_matches_list in matches:
    if len(sent_matches_list) > 1:
        n_multiple_matches+=1

print(n_multiple_matches)

2017

In [15]:
# first 5 examples of sentence, elative construction phrase match and syntactic head of the phrase
for i in range(len(match_sentences)):
    if i == 5:
        break
    display_example(i, match_sentences, matches)

Mis selle pronksist kujuga ikka juhtuda sai . . . ”
pronksist kujuga
kujuga

Mori nimetatud uues valitsuses jääb endiselt rahandusministri ametisse 81-aastane ekspeaminister Kiichi Miyazawa ning veteranist välisminister Yohei Kono .
veteranist välisminister
välisminister

Priit Press , floristist ettevõtja Aegajalt tunnen puudust , sest üleliia ei ole raha kunagi , kuid ma ei tee sellest probleemi .
floristist ettevõtja
ettevõtja

Oleme tuttavad lasteaiast saadik , viimased 10 aastat oleme koos olnud .
lasteaiast saadik
saadik

Vastassoost partneri valikul otsitakse tavaliselt vastavale soorollile tüüpilise käitumise väljendamist .
Vastassoost partneri
partneri

In [16]:
# list of specified members of construction examples
conx_member_list = [[get_conx_member(match, "A") for idx2, match in enumerate(matches[idx1])] for idx1, sent in enumerate(match_sentences)]
print(conx_member_list[0])

# list of specified members of construction examples as lemmas
conx_member_lemma_list = [[member.morph_analysis.lemma[0] for member in members] for idx1, members in enumerate(conx_member_list)]
print(conx_member_lemma_list[0])

# flattened version of member lemma list
lemma_list = [member for members in conx_member_lemma_list for member in members]
print(lemma_list[0])

[Span('pronksist', [{'id': 3, 'lemma': 'pronks', 'upostag': 'S', 'xpostag': 'S', 'feats': {'el': 'el', 'sg': 'sg', 'com': 'com'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}])]
['pronks']
pronks

In [17]:
# Lists of material and occupation/nationality/role lemmas
SEM_DATA_PATH = "../data/semantic_categories/"
FILENAME1 = "material.txt"
FILENAME2 = "occupation_nationality_role.txt"

material: list[str] = read_txt_to_list(f"{SEM_DATA_PATH}{FILENAME1}")
occupation_nationality_role: list[str] = read_txt_to_list(f"{SEM_DATA_PATH}{FILENAME2}")

In [18]:
# Filtering and categorizing pattern match lemmas
elative_material_attribute: list[str] = get_filtered_list(lemma_list, material+occupation_nationality_role)

In [19]:
# pattern match lemmas that do not occur among material nor attribute lemmas
elative_other = list(set(lemma_list).difference(set(elative_material_attribute)))

In [20]:
len(elative_material_attribute)

40137

In [21]:
len(elative_other)

15487

In [46]:
phrases = []
for idx1, sent_matches in enumerate(matches):
    for idx2, match in enumerate(sent_matches):
        if match["A"].lemma in elative_material_attribute:
            phrases.append("##".join([match["A"].text, match["B"].text]))

In [22]:
phrases2 = []
for idx1, sent_matches in enumerate(matches):
    for idx2, match in enumerate(sent_matches):
        if match["A"].lemma in elative_other:
            phrases2.append("##".join([match["A"].text, match["B"].text]))

In [47]:
len(phrases)

39705

In [23]:
len(phrases2)

50255

In [48]:
print(phrases[0])

pronksist##kujuga

In [24]:
print(phrases2[0])

floristist##ettevõtja

In [49]:
phrase_freqs = Counter(phrases).most_common()

In [25]:
phrase_freqs2 = Counter(phrases2).most_common()

In [50]:
phrase_freqs[0]

('isikust##ettevõtja', 1004)

In [26]:
phrase_freqs2[0]

('plika_tartust##afk', 2189)

In [51]:
data = []

for idx, phrase_freq in enumerate(phrase_freqs):
    phrase = phrase_freq[0].split("##")   
    if len(phrase) != 2:
        continue   
    freq = phrase_freq[1]
    data_dct = {
                "member1": phrase[0], 
                "member2": phrase[1],
                "freq": freq
                }
    data.append(data_dct)

In [27]:
data2 = []

for idx, phrase_freq in enumerate(phrase_freqs2):
    phrase = phrase_freq[0].split("##")   
    if len(phrase) != 2:
        continue   
    freq = phrase_freq[1]
    data_dct = {
                "member1": phrase[0], 
                "member2": phrase[1],
                "freq": freq
                }
    data2.append(data_dct)

In [52]:
data[0]

{'member1': 'isikust', 'member2': 'ettevõtja', 'freq': 1004}

In [28]:
data2[0]

{'member1': 'plika_tartust', 'member2': 'afk', 'freq': 2189}

In [54]:
with open('../derived_data/elative_construction/elative_construction_phrase_list.csv', 'w', encoding='utf-8', newline='') as csvfile:
    fieldnames = ['member1', 'member2', 'freq']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data)

In [29]:
with open('../derived_data/elative_construction/elative_construction_not_material_attribute_phrase_list.csv', 'w', encoding='utf-8', newline='') as csvfile:
    fieldnames = ['member1', 'member2', 'freq']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data2)