In [1]:
import sqlite3
import pandas as pd
import os
import csv

In [2]:

DATABASE = "../../drive_data_v1/v33_koondkorpus_sentences_verb_pattern_obl_20241002-130310_test.db"

OBL_TABLE = "spatial_obl"

FILTERED_CLASS_TABLE = f"spatial_obl_n_random_100k_lemma"

FNAME = f"n_random_100k_lemma"
LARGE_DATA_FILE = f"../data/n_random/{FNAME}.csv"
LARGE_DATA_FILE_SORTED = f"../data/n_random/{FNAME}_sorted.csv"

### andmetabelid

In [3]:
conn = sqlite3.connect(DATABASE)
cursor = conn.cursor()

### 100K random lemmat ja nende laused

In [4]:

query = f"""SELECT *FROM {OBL_TABLE}"""

filtered_class = pd.read_sql(query, conn)
filtered_class

,id,sentence_id,head_id,row_loc,verb,verb_compound,feats,pos,lemma,form,status,ekilex_tag,ner_tag,timex_tag,morph_case,tags,sentence
0,1,3,2,3,toimuma,,"com,in,sg",S,lõpp,lõpus,,None,None,DATE,in,|T|AT|ET|LT|ST|AET|ALT|AST|ELT|LST|,Kaheksakümnendate aastate lõpus toimus Türi 1.
1,7,5,3,12,saama,pihta,"all,com,pl",S,keel,keeltele,,None,None,None,all,,"Bändi , mille solist ei osanud laulda , kidram..."
2,19,10,10,4,tulema,,"ad,sg",P,sina,sul,,None,None,None,ad,,Kui sageli tuli sul kooli juhtkonna ees aru an...
3,22,12,11,3,viilima,,"com,el,pl",S,tund,tundidest,,None,None,None,el,,Ma viilisin tundidest igal võimalikul juhul .
4,23,12,11,6,viilima,,"ad,com,sg",S,juht,juhul,,None,None,None,ad,,Ma viilisin tundidest igal võimalikul juhul .
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7842657,54050467,21424522,30078975,9,minema,,"adit,com,sg",S,perse,perse,,None,None,None,adit,,devilgirl_unes: ta ytles mulle sittarott ja mi...
7842658,54050472,21424522,30078981,31,rääkima,,"all,sg",P,sina,sulle,,None,None,None,all,,devilgirl_unes: ta ytles mulle sittarott ja mi...
7842659,54050473,21424522,30078981,33,rääkima,,"abl,com,sg",S,tege,tegelt,,None,None,None,abl,,devilgirl_unes: ta ytles mulle sittarott ja mi...
7842660,54050478,21424523,30078982,9,minema,,"adit,com,sg",S,tyll,tylli,,None,None,None,adit,,devilgirl_unes: ja sa ära mine seepärast temag...
7842661,54050490,21424528,30078989,8,ütlema,,"all,sg",P,mina,mulle,,None,None,None,all,,ulluke: < zum_zum > kuule kui sa ütled mulle v...

In [18]:
# shuffle
#df = filtered_class.groupby("lemma").sample(frac=1, random_state=1, replace=False)
sample = (
    filtered_class.sample(frac=1, random_state=1)
      .drop_duplicates("lemma")
      .head(100000)
)

In [19]:
sample

,id,sentence_id,head_id,row_loc,verb,verb_compound,feats,pos,lemma,form,status,ekilex_tag,ner_tag,timex_tag,morph_case,tags,sentence
3032984,19015731,6330145,10170924,15,nõrgendama,,"com,in,sg",S,plaan,plaanis,,None,None,None,in,,"See killustaks meie niigi piiratud ressursse ,..."
776053,4961188,1670465,2660016,6,lahkuma,,"adit,com,sg",S,kaitsevägi,kaitseväkke,,organisation,None,None,adit,|L|AL|EL|LS|LT|ALT|ELT|LST|,"Kõuts tunnistas , et lahkuks kaitseväkke raske..."
3027116,18978102,6317069,10150410,9,liikuma,edasi,"ad,com,sg",S,juhtimine,juhtimisel,,None,None,None,ad,,"Või siis "" Res Publica liigub edasi Rahumäe ju..."
7550771,50932496,18516053,28038358,10,maksma,,"all,pl",P,sina,teile,,None,None,None,all,,"Austatud opositsioon , ärge tehke nii , see ma..."
1694509,10655338,3538144,5697858,15,algama,,"com,el,sg",S,rubla,rublast,,None,None,None,el,,"Valitsuse algatatud reformi vastased leiavad ,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1342139,8449558,2810055,4506265,3,huvituma,,"all,com,sg",S,automaksupoliitika,automaksupoliitikale,,None,None,None,all,,Tänu Soome automaksupoliitikale huvituvad soom...
6324052,41225023,13997196,22282465,14,töötama,,"ad,com,sg",S,sõjaväebaasiterritoorium,sõjaväebaasiterritooriumil,,None,None,None,ad,,Nagu igal araabia maal on ka Iraagis olemas tu...
89732,643871,225745,364952,7,käituma,,"com,in,sg",S,käsuvoog,käsuvoos,,None,None,None,in,,"Oluline on teada , kuidas käituvad käsuvoos su..."
234955,1584582,563553,891354,18,sulistama,,"com,in,sg",S,allikavesi,allikavees,,None,None,None,in,,"Mõned hõl-juvad pilvedes , teised hiilivad maa..."
3327872,20883948,6968252,11195930,1,siduma,,"el,prop,sg",S,Carita,Caritast,,None,None,None,el,,Caritast seob Viljandi vanglaga pikaajaline ko...

In [22]:
len(filtered_class["lemma"].value_counts())

245358

In [20]:
len(sample["lemma"].value_counts())

100000

In [21]:
len(sample["sentence"].value_counts())

99409

In [24]:
sample[sample["verb"]=="abielluma"]

,id,sentence_id,head_id,row_loc,verb,verb_compound,feats,pos,lemma,form,status,ekilex_tag,ner_tag,timex_tag,morph_case,tags,sentence
2178025,13665319,4556396,7323918,4,abielluma,,"com,in,sg",S,perekonnaseisuosakond,perekonnaseisuosakonnas,,None,None,None,in,,Ka Pärnu maavalitsuse perekonnaseisuosakonnas ...
5476255,35612962,12048238,19285711,11,abielluma,,"abl,sg",P,30see,30selt,,None,None,None,abl,,« Nõukogude ajal räägiti nagu imeasja ameerikl...
4406772,28522528,9610589,15425888,1,abielluma,,"ad,com,pl",S,putshipäev,Putshipäevadel,,None,None,None,ad,,Putshipäevadel abiellusid Haapsalus Siiri ning...
5753783,37431449,12659560,20255774,20,abielluma,,"in,prop,sg",S,Telluride,Telluride'is,,None,LOC,None,in,|L|AL|EL|LS|LT|ALT|ELT|LST|,Paar kohtus esimest korda 1990. aastal filmi “...
518585,3357171,1144004,1817887,8,abielluma,,"com,in,sg",S,suite,suite'is,,None,None,None,in,,Me abiellusime 30. juunil roosas no wedding su...
7259603,48479793,17247911,26481886,4,abielluma,,"in,prop,sg",S,Curitiba,Curitibas,,None,None,None,in,,1998 abiellusid Brasiilias Curitibas 90 cm ...
3034436,19025127,6333071,10176006,6,abielluma,,"com,el,sg",S,armeeohvitser,armeeohvitserist,,alive,None,None,el,|A|AE|AL|AS|AT|AET|ALT|AST|,Kaks aastat hiljem abiellus Camilla armeeohvit...
7063691,46883030,16561072,25541323,2,abielluma,,"ad,com,sg",S,millenniumiöö,millenniumiööl,,None,None,None,ad,,Abiellus millenniumiööl
2781978,17435792,5809384,9321077,26,abielluma,,"com,in,sg",S,karaoke-baar,karaoke-baaris,,None,None,None,in,,Tõelise maalimamehena on Jimi elanud Berliinis...
1791441,11270771,3744908,6031122,15,abielluma,,"com,ill,sg",S,naisõpetaja,naisõpetajasse,,alive,None,None,ill,|A|AE|AL|AS|AT|AET|ALT|AST|,Konservatiivses Eestis eitas Anna ühiskonna su...
6010636,39148355,13229069,21165387,8,abielluma,,"com,in,sg",S,troonipärimisjärjekord,troonipärimisjärjekorras,,None,None,None,in,,"Nende meelest on skandaalne see , et troonipär..."
3504174,22149901,7408817,11893890,37,abielluma,,"in,prop,sg",S,Kaanan,Kaananis,,location,LOC,None,in,|L|AL|EL|LS|LT|ALT|ELT|LST|,"Jah , nad seisavad ümber püha paari , tühjas j..."
1797806,11310924,3758071,6052691,18,abielluma,,"in,prop,sg",S,Hamptons,Hamptonsis,,None,LOC,None,in,|L|AL|EL|LS|LT|ALT|ELT|LST|,Briti kõmulehe The Daily Mail teatel abiellus ...

In [25]:
sample.to_sql(FILTERED_CLASS_TABLE, conn, if_exists="replace", index=False)

100000

In [26]:
sample["morph_case"].value_counts()

morph_case
in      24990
el      23756
all     20401
ad      16970
adit     4828
ill      4554
abl      4501
Name: count, dtype: int64

In [28]:
sample.to_csv(LARGE_DATA_FILE, encoding="utf-8", index = False,sep=",", quoting=csv.QUOTE_MINIMAL)

In [29]:
conn.close()

In [30]:
df2 = pd.read_csv(LARGE_DATA_FILE, encoding="utf-8", sep=",")

In [20]:
#df2.head()

In [31]:
counts2 = df2.groupby(['verb','verb_compound', 'morph_case'], dropna=False).size().reset_index(name='count').sort_values('count', ascending=False)
counts2

           verb verb_compound morph_case  count
7527      saama           NaN         el   2195
254       andma           NaN        all   1161
7319    rääkima           NaN         el   1089
9309     tulema           NaN         ad    745
3460      käima           NaN         in    743
...         ...           ...        ...    ...
72        ajama         lahti         el      1
73        ajama        laiali         ad      1
10922  ühenduma           NaN         in      1
10923  ühilduma           NaN        abl      1
57       aitama         välja         in      1

[11006 rows x 4 columns]