# Checking tables that are created in prep and during annotation

## example, tested on another db file, some results might differ from other notebooks

In [1]:
import sqlite3
import pandas as pd
import configparser

In [2]:
def load_config(path):
    """Loads config.
    """
    config = configparser.ConfigParser()
    status = config.read(path) 
    assert status == [path]
    return config

In [ ]:
config_f = "../conf/conf_ex_A.ini"
config = load_config(config_f)

# database file path
DB_FILE = config["configuration"]["database"]
#print(DB_FILE)

In [4]:
# connecting with database
conn = sqlite3.connect(DB_FILE)
cur = conn.cursor()

In [5]:
q1 = """
SELECT * FROM sqlite_master WHERE type='table'
"""
tables = pd.read_sql(q1, conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,collections_processed,collections_processed,2,CREATE TABLE collections_processed (tablename ...
1,table,sqlite_sequence,sqlite_sequence,5,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,transaction_row,transaction_row,7,CREATE TABLE `transaction_row` (`id` INTEGER P...
3,table,transaction_head,transaction_head,4,"CREATE TABLE ""transaction_head"" (\n""id"" INTEGE..."
4,table,spatial_obl,spatial_obl,1753090,"CREATE TABLE spatial_obl(\n id INT,\n senten..."
5,table,verb_case_counts_A,verb_case_counts_A,2763978,CREATE TABLE verb_case_counts_A (\n ...
6,table,verb_case_percentages_A,verb_case_percentages_A,2764543,"CREATE TABLE ""verb_case_percentages_A"" (\n""ver..."
7,table,verb_case_log_A,verb_case_log_A,2764813,"CREATE TABLE ""verb_case_log_A"" (\n""verb"" TEXT,..."
8,table,verb_case_counts_E,verb_case_counts_E,2765414,CREATE TABLE verb_case_counts_E (\n ...
9,table,verb_case_percentages_E,verb_case_percentages_E,2766042,"CREATE TABLE ""verb_case_percentages_E"" (\n""ver..."
10,table,verb_case_log_E,verb_case_log_E,2766306,"CREATE TABLE ""verb_case_log_E"" (\n""verb"" TEXT,..."
11,table,verb_case_counts_EL,verb_case_counts_EL,2766626,CREATE TABLE verb_case_counts_EL (\n ...
12,table,verb_case_percentages_EL,verb_case_percentages_EL,2767255,"CREATE TABLE ""verb_case_percentages_EL"" (\n""ve..."
13,table,verb_case_log_EL,verb_case_log_EL,2767543,"CREATE TABLE ""verb_case_log_EL"" (\n""verb"" TEXT..."
14,table,verb_case_counts_ELT,verb_case_counts_ELT,2767859,CREATE TABLE verb_case_counts_ELT (\n ...
15,table,verb_case_percentages_ELT,verb_case_percentages_ELT,2768490,"CREATE TABLE ""verb_case_percentages_ELT"" (\n""v..."
16,table,verb_case_log_ELT,verb_case_log_ELT,2768766,"CREATE TABLE ""verb_case_log_ELT"" (\n""verb"" TEX..."
17,table,verb_case_counts_L,verb_case_counts_L,2769085,CREATE TABLE verb_case_counts_L (\n ...
18,table,verb_case_percentages_L,verb_case_percentages_L,2769711,"CREATE TABLE ""verb_case_percentages_L"" (\n""ver..."
19,table,verb_case_log_L,verb_case_log_L,2769998,"CREATE TABLE ""verb_case_log_L"" (\n""verb"" TEXT,..."
20,table,verb_case_counts_S,verb_case_counts_S,2770312,CREATE TABLE verb_case_counts_S (\n ...
21,table,verb_case_percentages_S,verb_case_percentages_S,2770947,"CREATE TABLE ""verb_case_percentages_S"" (\n""ver..."
22,table,verb_case_log_S,verb_case_log_S,2771201,"CREATE TABLE ""verb_case_log_S"" (\n""verb"" TEXT,..."
23,table,verb_case_counts_T,verb_case_counts_T,2771522,CREATE TABLE verb_case_counts_T (\n ...
24,table,verb_case_percentages_T,verb_case_percentages_T,2772152,"CREATE TABLE ""verb_case_percentages_T"" (\n""ver..."
25,table,verb_case_log_T,verb_case_log_T,2772427,"CREATE TABLE ""verb_case_log_T"" (\n""verb"" TEXT,..."
26,table,verb_case_unique_lemmas,verb_case_unique_lemmas,2765027,"CREATE TABLE ""verb_case_unique_lemmas"" (\n""ver..."
27,table,confidence_values,confidence_values,2772745,"CREATE TABLE ""confidence_values"" (\n""x"" INTEGE..."
28,table,spatial_obl_plotting_examples,spatial_obl_plotting_examples,2773084,"CREATE TABLE ""spatial_obl_plotting_examples"" (..."
29,table,spatial_obl_A_n_class_wide,spatial_obl_A_n_class_wide,2795022,"CREATE TABLE ""spatial_obl_A_n_class_wide"" (\n""..."
30,table,spatial_obl_A_n_class,spatial_obl_A_n_class,2796178,"CREATE TABLE ""spatial_obl_A_n_class"" (\n""verb""..."
31,table,spatial_obl_ELT_n_class_wide,spatial_obl_ELT_n_class_wide,2797038,"CREATE TABLE ""spatial_obl_ELT_n_class_wide"" (\..."
32,table,spatial_obl_ELT_n_class,spatial_obl_ELT_n_class,2798197,"CREATE TABLE ""spatial_obl_ELT_n_class"" (\n""ver..."
33,table,spatial_obl_S_n_class_wide,spatial_obl_S_n_class_wide,2799059,"CREATE TABLE ""spatial_obl_S_n_class_wide"" (\n""..."
34,table,spatial_obl_S_n_class,spatial_obl_S_n_class,2800218,"CREATE TABLE ""spatial_obl_S_n_class"" (\n""verb""..."

In [34]:
#cur.execute(f"DROP TABLE if exists 'ELT_n80_max_v01'")
#conn.commit()

In [6]:
### transaction_row

query = f"SELECT count(*) FROM transaction_row"
tr_rows = pd.read_sql(query, conn)
print(tr_rows)

query = f"SELECT * FROM transaction_row limit 10"
tr = pd.read_sql(query, conn)
tr

   count(*)
0  54050499

,id,head_id,loc,loc_rel,deprel,form,lemma,feats,parent_loc,pos,sentence_id,status,ekilex_tag,ner_tag,timex_tag
0,1,2,3,-1,obl,lõpus,lõpp,"com,in,sg",None,S,3,,None,None,DATE
1,2,2,5,1,nsubj,Türi,Türi,"gen,prop,sg",None,S,3,syntax-morph conflict,None,LOC,None
2,3,2,6,2,obl,1.,1.,"<?>,ord,roman",None,N,3,,None,None,None
3,4,3,1,-3,obj,Bändi,bänd,"adit,com,sg",None,S,5,syntax-morph conflict,None,None,None
4,5,3,9,-2,nsubj,kidramees,kidramees,"com,nom,sg",None,S,5,,None,None,None
5,6,3,10,-1,aux,ei,ei,"aux,neg",None,V,5,,None,None,None
6,7,3,12,1,obl,keeltele,keel,"all,com,pl",None,S,5,,None,None,None
7,8,3,13,2,compound:prt,pihta,pihta,,None,D,5,,None,None,None
8,9,4,4,-2,nsubj,solist,solist,"com,nom,sg",None,S,5,,None,None,None
9,10,4,5,-1,aux,ei,ei,"aux,neg",None,V,5,,None,None,None

In [7]:
### transaction_head

query = f"SELECT count(*) FROM transaction_head"
th_rows = pd.read_sql(query, conn)
print(th_rows)

query = f"SELECT * FROM transaction_head limit 10"
th = pd.read_sql(query, conn)
th

   count(*)
0  30078992

,id,sentence_id,loc,verb,verb_compound,form,deprel,feats,phrase
0,1,1,4,olema,,on,cop,"af,indic,mod,pl,pres,ps,ps3",on
1,2,3,4,toimuma,,toimus,root,"af,aux,impf,indic,ps,ps3,sg",lõpus toimus Türi 1.
2,3,5,11,saama,pihta,saanud,root,"aux,partic,past,ps",Bändi kidramees ei saanud keeltele pihta
3,4,5,6,oskama,,osanud,acl:relcl,"mod,partic,past,ps",solist ei osanud laulda
4,5,5,17,olema,,oli,conj,"af,impf,indic,main,ps,ps3,sg",eesmärk oli teha
5,6,6,2,kulmineeruma,,kulmineerus,root,"af,impf,indic,main,ps,ps3,sg",Esinemine kulmineerus purukspeksmisega
6,7,7,2,lõpetama,,lõpetas,root,"af,impf,indic,mod,ps,ps3,sg",Kaose lõpetas miilits
7,8,8,5,olema,,oli,cop,"af,impf,indic,mod,ps,ps3,sg",oli
8,9,8,21,olema,,on,cop,"af,indic,main,pl,pres,ps,ps3",on
9,10,10,3,tulema,,tuli,root,"af,aux,impf,indic,ps,ps3,sg",sageli tuli sul anda

In [8]:
### spatial_obl

query = f"SELECT count(*) FROM spatial_obl"
so_rows = pd.read_sql(query, conn)
print(so_rows)

query = f"SELECT * FROM spatial_obl limit 10"
so = pd.read_sql(query, conn)
so

   count(*)
0   7842662

,id,sentence_id,head_id,row_loc,verb,verb_compound,feats,pos,lemma,form,status,ekilex_tag,ner_tag,timex_tag,morph_case,tags,sentence
0,1,3,2,3,toimuma,,"com,in,sg",S,lõpp,lõpus,,None,None,DATE,in,|T|AT|ET|LT|ST|AET|ALT|AST|ELT|LST|,Kaheksakümnendate aastate lõpus toimus Türi 1.
1,7,5,3,12,saama,pihta,"all,com,pl",S,keel,keeltele,,None,None,None,all,,"Bändi , mille solist ei osanud laulda , kidram..."
2,19,10,10,4,tulema,,"ad,sg",P,sina,sul,,None,None,None,ad,,Kui sageli tuli sul kooli juhtkonna ees aru an...
3,22,12,11,3,viilima,,"com,el,pl",S,tund,tundidest,,None,None,None,el,,Ma viilisin tundidest igal võimalikul juhul .
4,23,12,11,6,viilima,,"ad,com,sg",S,juht,juhul,,None,None,None,ad,,Ma viilisin tundidest igal võimalikul juhul .
5,40,21,25,1,muutuma,,"el,sg",P,mis,Millest,,None,None,None,el,,Millest selline muutus ?
6,59,25,33,12,minema,peale,"all,com,sg",S,rahvas,rahvale,,alive,None,None,all,|A|AE|AL|AS|AT|AET|ALT|AST|,"Tegutsesin siis diskorina ja nägin , et eurobi..."
7,69,29,37,6,tekkima,,"el,sg",P,see,sellest,,None,None,None,el,,Pidevalt tantsumusa sees olles tekib sellest k...
8,85,37,51,8,kutsuma,,"adit,com,sg",S,elu,ellu,,None,None,None,adit,,"Pole välistatud , et me pundi kunagi ellu kuts..."
9,88,39,53,4,tulema,,"adit,com,sg",S,toim,toime,,None,None,None,adit,,Kuidas sa rahaliselt toime tuled ?

In [ ]:
# kui palju on spatial obl tabelis lõkse (verb+comp+morph_case)

In [9]:
query = f"SELECT verb, verb_compound, morph_case FROM spatial_obl group by verb, verb_compound, morph_case"

res = pd.read_sql(query, conn)
res

                 verb verb_compound morph_case
0            0muutuma                       el
1              0olema                       ad
2              0olema                       el
3              0olema                       in
4            10halama                       in
...               ...           ...        ...
74807  žestikuleerima                       ad
74808      žisraelima                       ad
74809     žongleerima                       ad
74810     žongleerima                       in
74811       хnnestuma                       in

[74812 rows x 3 columns]

In [ ]:
# spatial_obl_A_n_class, spatial_obl_S_n_class, spatial_obl_ELT_n_class
# nendest tabelistest on võetud n80 ja n50 jaoks andmed iga tag-i jaoks
# ja pandud scatterplotile

In [10]:
# kui palju lõkse on scatterplotil
# spatial_obl_A_n_class == spatial_obl_S_n_class == spatial_obl_ELT_n_class lõksude mõttes

query = f"SELECT verb, verb_compound, morph_case FROM spatial_obl_A_n_class"

res1 = pd.read_sql(query, conn)
res1

            verb verb_compound morph_case
0         aasima                       ad
1         aasima                       in
2      abielluma                      abl
3      abielluma                       ad
4      abielluma                     adit
...          ...           ...        ...
21572  šokeerima                      all
21573  šokeerima                       el
21574  šokeerima                       in
21575    šoppama                       in
21576  šveitsima                       in

[21577 rows x 3 columns]

In [11]:
query = f"SELECT verb, verb_compound, morph_case FROM spatial_obl_S_n_class"

res2 = pd.read_sql(query, conn)
res2

            verb verb_compound morph_case
0         aasima                       ad
1         aasima                       in
2      abielluma                      abl
3      abielluma                       ad
4      abielluma                     adit
...          ...           ...        ...
21572  šokeerima                      all
21573  šokeerima                       el
21574  šokeerima                       in
21575    šoppama                       in
21576  šveitsima                       in

[21577 rows x 3 columns]

In [12]:
query = f"SELECT verb, verb_compound, morph_case FROM spatial_obl_ELT_n_class"

res3 = pd.read_sql(query, conn)
res3

            verb verb_compound morph_case
0         aasima                       ad
1         aasima                       in
2      abielluma                      abl
3      abielluma                       ad
4      abielluma                     adit
...          ...           ...        ...
21572  šokeerima                      all
21573  šokeerima                       el
21574  šokeerima                       in
21575    šoppama                       in
21576  šveitsima                       in

[21577 rows x 3 columns]

In [13]:
res1.equals(res2)

True

In [14]:
res3.equals(res2)

True

In [36]:
query = f"SELECT * FROM spatial_obl_A_n_class where verb = 'saama' and verb_compound == ''"

res1 = pd.read_sql(query, conn)
res1

,verb,verb_compound,morph_case,log2_ratio,unique_lemmas,level,ann_unique_lemmas,not_ann_unique_lemmas,olulisus,my_tag,...,y_neg30,log2_y_pos30,y_pos20,y_neg20,log2_y_pos20,y_pos10,y_neg10,log2_y_pos10,not_ann_words,ann_words
0,saama,,abl,1.631782,2878,-,2045.0,2900.0,-,8017,...,1973,-1.124401,540,2338,-2.114244,262,2616,-3.319724,13737.0,8017.0
1,saama,,ad,-6.311530,1525,n10,275.0,3859.0,0.0,463,...,1037,-1.087463,279,1246,-2.158967,133,1392,-3.387661,38137.0,463.0
2,saama,,adit,-3.744161,370,n10,65.0,1053.0,0.02989,135,...,243,-0.936128,62,308,-2.312590,28,342,-3.610498,21842.0,135.0
3,saama,,all,0.280632,1711,n70,1035.0,3940.0,1.0,2557,...,1165,-1.093357,315,1396,-2.147875,151,1560,-3.368926,25586.0,2557.0
4,saama,,ill,-3.819115,428,n10,35.0,724.0,0.00786,96,...,283,-0.964749,72,356,-2.305808,33,395,-3.581315,2687.0,96.0
5,saama,,in,-5.285762,3152,n10,204.0,5593.0,0.0,720,...,2163,-1.128991,594,2558,-2.106481,288,2864,-3.313891,29886.0,720.0

In [15]:
query = f"SELECT * FROM verb_case_counts_ELT where verb_case_count > 4 and annotated != 0"

res4 = pd.read_sql(query, conn)
res4

,verb,verb_compound,morph_case,my_tag,other_tags,annotated,not_annotated,verb_case_count
0,aasima,,ad,2,0,2,6,8
1,aasima,,in,2,1,3,4,7
2,abielluma,,abl,2,0,2,101,103
3,abielluma,,ad,948,8,956,226,1182
4,abielluma,,adit,2,12,14,9,23
...,...,...,...,...,...,...,...,...
21573,šokeerima,,all,1,0,1,5,6
21574,šokeerima,,el,0,4,4,12,16
21575,šokeerima,,in,29,0,29,20,49
21576,šoppama,,in,2,0,2,3,5
21577,šveitsima,,in,2,0,2,4,6

In [33]:
query = f"SELECT * FROM verb_case_counts_ELT where verb == 'saama' and verb_compound == '' and verb_case_count > 4 and annotated != 0"

res4 = pd.read_sql(query, conn)
res4

,verb,verb_compound,morph_case,my_tag,other_tags,annotated,not_annotated,verb_case_count
0,saama,,abl,2414,8190,10604,13737,24341
1,saama,,ad,36530,707,37237,38137,75374
2,saama,,adit,1780,164,1944,21842,23786
3,saama,,all,1872,2790,4662,25586,30248
4,saama,,el,16046,8921,24967,75405,100372
5,saama,,ill,1337,114,1451,2687,4138
6,saama,,in,27611,1196,28807,29886,58693

In [26]:
query = f"SELECT distinct verb, verb_compound, morph_case FROM verb_case_counts_ELT where verb_case_count > 4 and annotated != 0"

res4 = pd.read_sql(query, conn)
res4

            verb verb_compound morph_case
0         aasima                       ad
1         aasima                       in
2      abielluma                      abl
3      abielluma                       ad
4      abielluma                     adit
...          ...           ...        ...
21573  šokeerima                      all
21574  šokeerima                       el
21575  šokeerima                       in
21576    šoppama                       in
21577  šveitsima                       in

[21578 rows x 3 columns]

In [ ]:
conn.close()