## Creating negation patterns

Creating a new database of negation patterns and corresponding '*feats*' values tables. The tables will be created using negation tables from *neg_tables.db*.

In [1]:
import sys
sys.path.append('../../../common_code')

In [2]:
import sqlite3
from paths import PATH_ROOT
from db_operations.verb_transactions.neg_patterns_creation import *
from db_operations.db_display import *

## Input parameters

In [3]:
INPUT_DIR = "C:/Users/liivas/Documents/Töö/verbirektisoonid/db_operations/workflows/002_verb_negations/development"

RESULT_DB = "neg_patterns.db"
NEG_TABLES_DB = f"{INPUT_DIR}/neg_tables.db"

## Data processing

In [4]:
con = sqlite3.connect(RESULT_DB)
cur = con.cursor()

cur.execute(f'ATTACH DATABASE "{NEG_TABLES_DB}" AS neg_tables')

create_neg_patterns(
    con,
    cur,
    verb_neg='neg_tables.verb_neg',
    verb_neg_phrases='neg_tables.verb_neg_phrases'
    )
con.close()

## Result

In [5]:
display_sqlite_as_dataframe(RESULT_DB, 'neg_patterns', 10)

   pat_id    form     deprel
0       1    pole       root
1       2  polnud       root
2       3  poleks       root
3       4  polnud  parataxis
4       5    pole      advcl
5       6  polnud      ccomp
6       7    pole  parataxis
7       8    pole       conj
8       9    pole  acl:relcl
9      10  polnud  acl:relcl

In [6]:
display_sqlite_as_dataframe(RESULT_DB, 'neg_feats', 10)

   pat_id                         feats
0       1         aux,indic,neg,pres,ps
1       1        indic,main,neg,pres,ps
2       2        impf,indic,main,neg,ps
3       3         cond,main,neg,pres,ps
4       4         aux,impf,indic,neg,ps
5       1  aux,imper,neg,pres,ps,ps2,sg
6       5        indic,main,neg,pres,ps
7       6         aux,impf,indic,neg,ps
8       5  aux,imper,neg,pres,ps,ps2,sg
9       5         aux,indic,neg,pres,ps

## Additional documentation

In [7]:
?create_neg_patterns