In [1]:
import sqlite3
import pandas as pd
from tqdm import tqdm
import powerlaw as pwl
from collections import Counter
import matplotlib.pyplot as plt
import numpy as np
import os
from estnltk import Text
from estnltk.storage.postgres import PostgresStorage, create_schema

from read_config import read_config

In [2]:
con = sqlite3.connect("vp_data2_isikud.db")
cur = con.cursor()
cur.execute('ATTACH DATABASE "v33.db" AS v33')

## koondkorpus

In [3]:
root = os.getcwd()
file_name = "conf_minu.ini"
if os.path.isfile(file_name):
    fname = os.path.basename(file_name).split('/')[-1]
    config = read_config(fname, file_name)
else:
    print("Could not find the specified configuration file.")
    raise SystemExit

In [4]:
source_storage = PostgresStorage(host=config["source_database"]["host"],
                          port=config["source_database"]["port"],
                          dbname=config["source_database"]["database_name"],
                          user=config["source_database"]["username"],
                          password=config["source_database"]["password"],
                          schema=config["source_database"]["work_schema"], 
                          role=config["source_database"]["role"],
                          temporary=False)

INFO:storage.py:57: connecting to host: 'postgres.keeleressursid.ee', port: '5432', dbname: 'estonian-text-corpora', user: 'koljalka'
INFO:storage.py:108: schema: 'estonian_text_corpora', temporary: False, role: 'estonian_text_corpora_read'

In [20]:
source_storage

In [45]:
collection = source_storage['koondkorpus_sentences']

## base tabel kus on verb, kääne, elus_cnt, koht_cnt, distinct root count

In [4]:
query = """

SELECT *
from transactions_verbs_obl_kohakaandes_eluskoht_root_counts_distinct_base_wcomps_v1 
"""

source3 = pd.read_sql_query(query, con)
#source3

In [5]:
source3["elus_div"] = source3["elus_cnt"]/source3["root_cnt"]
source3["koht_div"] = source3["koht_cnt"]/source3["root_cnt"]

In [6]:
source3["kaane2"] = ''

source3.loc[source3['kaane'] == 'ill', 'kaane2'] = 'sisse'
source3.loc[source3['kaane'] == 'in', 'kaane2'] = 'sees'
source3.loc[source3['kaane'] == 'el', 'kaane2'] = 'seest'
source3.loc[source3['kaane'] == 'all', 'kaane2'] = 'alale'
source3.loc[source3['kaane'] == 'ad', 'kaane2'] = 'alal'
source3.loc[source3['kaane'] == 'abl', 'kaane2'] = 'alalt'
source3.loc[source3['kaane'] == 'adit', 'kaane2'] = 'sisse'

# võtta konkreetsed näited mõnest kohast

####  näited, mis võiks olla kindlalt koht (rohelised punktid)

In [8]:
source3[(source3["root_cnt"]>=100) & (source3["elus_div"]<=0.05) & (source3["koht_div"]>=0.2)].sort_values(by=["koht_cnt"], ascending=False)

,verb,verb_compound,kaane,elus_cnt,koht_cnt,root_cnt,elus_div,koht_div,kaane2
959,kolima,,adit,9,94,427,0.021077,0.220141,sisse
1279,ööbima,,in,8,76,312,0.025641,0.243590,sees
1661,seadma,sisse,in,5,55,237,0.021097,0.232068,sees
1646,askeldama,,in,5,54,239,0.020921,0.225941,sees
1506,lõhkuma,,in,8,53,264,0.030303,0.200758,sees
1596,süütama,,in,11,50,248,0.044355,0.201613,sees
1725,peksma,,in,4,50,227,0.017621,0.220264,sees
2009,tormama,,adit,6,49,190,0.031579,0.257895,sisse
1747,levima,,ill,11,47,225,0.048889,0.208889,sisse
1753,valvama,,in,6,46,225,0.026667,0.204444,sees
2187,põgenema,,adit,7,41,173,0.040462,0.236994,sisse
2064,kostuma,,el,8,39,183,0.043716,0.213115,seest
2104,elutsema,,in,5,39,179,0.027933,0.217877,sees
2553,juhatama,,adit,7,38,142,0.049296,0.267606,sisse
2198,vaatama,ringi,in,4,38,172,0.023256,0.220930,sees
2713,paigaldama,,ill,4,37,133,0.030075,0.278195,sisse
2653,kõrguma,,in,4,37,136,0.029412,0.272059,sees
2578,tungima,kallale,in,3,37,141,0.021277,0.262411,sees
2067,meelitama,,ill,7,37,183,0.038251,0.202186,sisse
2235,helisema,,in,7,37,168,0.041667,0.220238,sees
2952,meelitama,,adit,6,34,120,0.050000,0.283333,sisse
2416,üürima,,in,1,34,153,0.006536,0.222222,sees
2353,passima,,in,7,33,157,0.044586,0.210191,sees
2991,kõndima,ringi,in,2,31,118,0.016949,0.262712,sees
2642,pidutsema,,in,1,30,137,0.007299,0.218978,sees
3154,laienema,,ill,4,29,111,0.036036,0.261261,sisse
2546,pesitsema,,ad,5,29,143,0.034965,0.202797,alal
2716,pöörduma,tagasi,adit,2,29,133,0.015038,0.218045,sisse
2834,seadma,sisse,ad,3,28,127,0.023622,0.220472,alal
3416,laiuma,,in,4,28,100,0.040000,0.280000,sees
2921,jalutama,ringi,in,2,27,121,0.016529,0.223140,sees
3016,rentima,,in,1,27,117,0.008547,0.230769,sees
3168,märatsema,,in,2,27,110,0.018182,0.245455,sees
3174,tunglema,,in,4,27,110,0.036364,0.245455,sees
3422,pussitama,,in,1,26,100,0.010000,0.260000,sees
3398,põgenema,,all,3,26,101,0.029703,0.257426,alale
3365,konutama,,in,4,26,102,0.039216,0.254902,sees
3261,redutama,,in,3,26,106,0.028302,0.245283,sees
3310,rajama,,adit,2,26,104,0.019231,0.250000,sisse
3270,võtma,kaasa,adit,4,25,106,0.037736,0.235849,sisse
2886,avanema,,abl,0,25,123,0.000000,0.203252,alalt
3263,sisenema,,all,2,25,106,0.018868,0.235849,alale
3356,avanema,,adit,3,24,102,0.029412,0.235294,sisse
2946,blokeerima,,in,3,24,120,0.025000,0.200000,sees
3286,patrullima,,in,5,23,105,0.047619,0.219048,sees
3133,sõidutama,,all,3,23,112,0.026786,0.205357,alale
3086,vägistama,,in,1,23,114,0.008772,0.201754,sees
3182,juhatama,,ill,3,22,109,0.027523,0.201835,sisse
3284,opereerima,,in,1,21,105,0.009524,0.200000,sees
3337,pöörduma,tagasi,all,2,21,103,0.019417,0.203883,alale
3374,pildistama,,in,4,21,102,0.039216,0.205882,sees
3431,tegema,lahti,in,5,20,100,0.050000,0.200000,sees

### võtame nt kolima + adit

võtta 2-3 näidet lausetest
- kus on koht
- kus on elus
- kus ei ole elus/koht otsust

- vaja saada kätte transaction_head sentence_id

- transaction head join transaction on head_id
- transaction deprel+kääne tingimus

In [51]:
query = """
SELECT 
distinct 
    head.id as head_id,
    head.sentence_id as sentence_id,
    head.verb,
    head.verb_compound as verb_compound,
    --head.loc as verb_loc,
    --tr.loc as root_loc,
    tr.deprel as root_deprel,
    'adit' as kaane,
    tr.lemma as root_lemma,
    tr.koht as koht,
    tr.elus as elus
    
from 
(select *
from transaction_v2
where deprel = 'obl'
and INSTR(',' || feats || ',', ',' || 'adit' || ',') > 0) as tr

join 

(select * from
v33.transaction_head
where 
verb == 'kolima'
and verb_compound == '') as head

on head.id = tr.head_id

"""

r1 = pd.read_sql_query(query, con)
r1

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
0,6815,4016,kolima,,obl,adit,maja,YES,UNK
1,8254,4762,kolima,,obl,adit,riik,YES,UNK
2,11461,6626,kolima,,obl,adit,maja,YES,UNK
3,11764,6782,kolima,,obl,adit,kasiinopealinn,UNK,UNK
4,12443,7230,kolima,,obl,adit,kabinet,YES,UNK
...,...,...,...,...,...,...,...,...,...
1600,29145599,19495889,kolima,,obl,adit,raplane,UNK,UNK
1601,29210285,19633019,kolima,,obl,adit,pealinn,YES,UNK
1602,29426857,20056424,kolima,,obl,adit,kõrvalmaja,YES,UNK
1603,29826341,20918120,kolima,,obl,adit,maja,YES,UNK
1604,29826724,20918856,kolima,,obl,adit,kant,YES,UNK

In [52]:
r1[r1["elus"]=='YES']

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
43,357977,220129,kolima,,obl,adit,selg,UNK,YES
57,627212,403090,kolima,,obl,adit,lasteaed,YES,YES
72,1011360,637148,kolima,,obl,adit,tiim,UNK,YES
571,9604394,5984655,kolima,,obl,adit,tiim,UNK,YES
629,10668198,6629880,kolima,,obl,adit,käsi,UNK,YES
804,14061211,8760022,kolima,,obl,adit,tall,UNK,YES
824,14404007,8959959,kolima,,obl,adit,tiim,UNK,YES
825,14409203,8962963,kolima,,obl,adit,naiskond,UNK,YES
887,15354835,9565989,kolima,,obl,adit,mets,YES,YES
954,16386388,10211861,kolima,,obl,adit,lasteaed,YES,YES
1064,17977517,11220258,kolima,,obl,adit,lasteaed,YES,YES
1137,19052164,11905309,kolima,,obl,adit,tiim,UNK,YES
1165,19445729,12144963,kolima,,obl,adit,tiim,UNK,YES
1261,20821218,13013694,kolima,,obl,adit,selg,UNK,YES
1302,21551226,13474869,kolima,,obl,adit,tiim,UNK,YES
1320,21731354,13590674,kolima,,obl,adit,tiim,UNK,YES
1389,22692985,14294369,kolima,,obl,adit,rühm,UNK,YES
1407,22963307,14520815,kolima,,obl,adit,kauplus,UNK,YES
1487,25310350,16368782,kolima,,obl,adit,tiim,UNK,YES

In [65]:
r1[(r1["elus"]=='UNK') & (r1["koht"]=='UNK')]

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
3,11764,6782,kolima,,obl,adit,kasiinopealinn,UNK,UNK
9,46309,26875,kolima,,obl,adit,Ålborg,UNK,UNK
13,56518,32881,kolima,,obl,adit,teine,UNK,UNK
14,57688,33609,kolima,,obl,adit,küll,UNK,UNK
15,58108,33856,kolima,,obl,adit,Tallinn,UNK,UNK
...,...,...,...,...,...,...,...,...,...
1595,28470447,18852269,kolima,,obl,adit,pool,UNK,UNK
1596,28476561,18856209,kolima,,obl,adit,osariik,UNK,UNK
1598,28586262,18933337,kolima,,obl,adit,küll,UNK,UNK
1599,28715828,19027739,kolima,,obl,adit,Kuressaare,UNK,UNK
1600,29145599,19495889,kolima,,obl,adit,raplane,UNK,UNK

# otsida koondkorpusest välja laused kindlalt koht

### näited kohtadest

In [58]:
collection[4016].text #maja

'Suklesed kolisid oma majja 1997. aastal , lõpliku viimistluse sai maja välimus aga alles eelmisel talvel .'

In [59]:
collection[7230].text # kabinet

'Augustis kolib ANNE VEESAAR Vanalinnastuudio direktori kabinetti .'

In [60]:
collection[20918856].text #kant

'kissy: kuhu kanti sa siis kolid'

### näited elusatest

In [61]:
collection[637148].text # tiim

'Vähi , kes eelmised aastad tegeles suuskade libisemisega , kolis šmigunide tiimi ning viis kaasa tarkuse ja info .'

In [62]:
collection[220129].text # selg

'Algselt elutsesid kirbud nahkhiirtel ja pääsukestel , hiljem kolisid samades koobastes elavate inimeste selga .'

In [63]:
collection[14294369].text # rühm

'Oma noored sportlased võib anda ajutiselt kellegi teise hoolde , kuid esiteks on ka ajutisele treenerile vaja lisakoormuse kompenseerimiseks palka ning teiseks kipub nii olema , et edukamad õpilased sellisel ajal lõplikult teise treeneri rühma kolivad .'

### näited mis pole kumbki

In [66]:
collection[18852269].text # pool

'Alumise korruse teise poolde kolis Saare raamatukogu .'

In [67]:
collection[33609].text # küll

'Tema maja Toompuiesteel sai Isamaaliidu kontoriks , tema ise aga kolis perega Kohila kanti , Lohu külla .'

In [68]:
collection[32881].text # teine

'Pätiperiood lõppes , kui Indrek kolis Kuressaare esimesest keskkoolist teise .'

##  näited, mis võiks olla enamuselt koht (kollased punktid)

In [84]:
source3[(source3["root_cnt"]>=100) & (source3["elus_div"]<=0.05) & (source3["koht_div"]>=0.1) & (source3["koht_div"]<0.2)]#.head(10)

,verb,verb_compound,kaane,elus_cnt,koht_cnt,root_cnt,elus_div,koht_div,kaane2
218,veetma,,in,22,156,1487,0.014795,0.104909,sees
228,korraldama,,in,25,150,1428,0.017507,0.105042,sees
341,levima,,in,26,110,1077,0.024141,0.102136,sees
374,paiknema,,in,21,125,995,0.021106,0.125628,sees
377,puhkema,,in,21,153,991,0.021191,0.154390,sees
...,...,...,...,...,...,...,...,...,...
3403,võtma,üles,in,1,13,101,0.009901,0.128713,sees
3414,külmuma,,in,3,15,100,0.030000,0.150000,sees
3423,rakenduma,,in,2,12,100,0.020000,0.120000,sees
3424,riivama,,ad,4,15,100,0.040000,0.150000,alal
3429,sõimama,,in,3,17,100,0.030000,0.170000,sees

### võtame nt korraldama + in

võtta 2-3 näidet lausetest
- kus on koht
- kus on elus
- kus ei ole elus/koht otsust

- vaja saada kätte transaction_head sentence_id

- transaction head join transaction on head_id
- transaction deprel+kääne tingimus

In [85]:
query = """
SELECT 
distinct 
    head.id as head_id,
    head.sentence_id as sentence_id,
    head.verb,
    head.verb_compound as verb_compound,
    --head.loc as verb_loc,
    --tr.loc as root_loc,
    tr.deprel as root_deprel,
    'adit' as kaane,
    tr.lemma as root_lemma,
    tr.koht as koht,
    tr.elus as elus
    
from 
(select *
from transaction_v2
where deprel = 'obl'
and INSTR(',' || feats || ',', ',' || 'in' || ',') > 0) as tr

join 

(select * from
v33.transaction_head
where 
verb == 'korraldama'
and verb_compound == '') as head

on head.id = tr.head_id

"""

r1 = pd.read_sql_query(query, con)
r1

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
0,2772,1547,korraldama,,obl,adit,internet,UNK,UNK
1,4788,2865,korraldama,,obl,adit,garaazh,YES,UNK
2,7834,4571,korraldama,,obl,adit,Pärnu,UNK,UNK
3,15801,9212,korraldama,,obl,adit,tele,UNK,UNK
4,27434,15859,korraldama,,obl,adit,Egiptus,UNK,UNK
...,...,...,...,...,...,...,...,...,...
6792,29230774,19675970,korraldama,,obl,adit,priva,UNK,UNK
6793,29318636,19857849,korraldama,,obl,adit,baar,UNK,UNK
6794,29902703,21066763,korraldama,,obl,adit,kodu,YES,UNK
6795,29923267,21100738,korraldama,,obl,adit,noortekas,UNK,UNK
6796,29972527,21203352,korraldama,,obl,adit,tutvum,UNK,UNK

In [91]:
r1[r1["koht"]=='YES'].head(20)

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
1,4788,2865,korraldama,,obl,adit,garaazh,YES,UNK
6,31461,18288,korraldama,,obl,adit,ruum,YES,UNK
17,81020,46989,korraldama,,obl,adit,pealinn,YES,UNK
18,81487,47266,korraldama,,obl,adit,elamu,YES,UNK
23,162476,96136,korraldama,,obl,adit,maa,YES,UNK
28,184091,109397,korraldama,,obl,adit,ruum,YES,UNK
34,216676,129368,korraldama,,obl,adit,kodu,YES,UNK
35,227112,135900,korraldama,,obl,adit,maja,YES,UNK
38,233949,140213,korraldama,,obl,adit,talu,YES,UNK
43,275764,165479,korraldama,,obl,adit,ruum,YES,UNK
46,313417,188880,korraldama,,obl,adit,kodu,YES,UNK
54,365588,226306,korraldama,,obl,adit,riik,YES,UNK
56,377600,235805,korraldama,,obl,adit,rajoon,YES,UNK
57,377916,236104,korraldama,,obl,adit,maa,YES,UNK
65,448951,284617,korraldama,,obl,adit,ruum,YES,UNK
68,449358,284943,korraldama,,obl,adit,ruum,YES,UNK
78,513409,331312,korraldama,,obl,adit,kool,YES,UNK
91,616643,396613,korraldama,,obl,adit,kodu,YES,UNK
93,635745,408535,korraldama,,obl,adit,maja,YES,UNK
95,644215,414049,korraldama,,obl,adit,maja,YES,UNK

In [87]:
r1[r1["elus"]=='YES'].head(20)

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
120,738173,470573,korraldama,,obl,adit,vabariik,UNK,YES
136,824662,523332,korraldama,,obl,adit,vaim,UNK,YES
296,1360790,853741,korraldama,,obl,adit,organism,UNK,YES
304,1392690,874350,korraldama,,obl,adit,kauplus,UNK,YES
534,2105087,1324204,korraldama,,obl,adit,tshehh,UNK,YES
670,2471377,1553135,korraldama,,obl,adit,Vabariik,UNK,YES
811,2875470,1806676,korraldama,,obl,adit,pere,UNK,YES
1013,3569601,2231342,korraldama,,obl,adit,mets,YES,YES
1028,3614108,2258108,korraldama,,obl,adit,mets,YES,YES
1042,3637650,2272271,korraldama,,obl,adit,mets,YES,YES
1261,4185387,2608334,korraldama,,obl,adit,tiib,UNK,YES
1467,4659185,2906519,korraldama,,obl,adit,politseiprefektuur,UNK,YES
1523,4850285,3023709,korraldama,,obl,adit,kauplus,UNK,YES
1705,5528260,3434018,korraldama,,obl,adit,regioon,YES,YES
1969,6371075,3956200,korraldama,,obl,adit,süda,UNK,YES
2036,6571490,4082575,korraldama,,obl,adit,kaitse,UNK,YES
2140,6833345,4247017,korraldama,,obl,adit,kauplus,UNK,YES
2291,7226852,4494705,korraldama,,obl,adit,mets,YES,YES
2692,8457176,5272171,korraldama,,obl,adit,kauplus,UNK,YES
2740,8616951,5372609,korraldama,,obl,adit,mets,YES,YES

In [98]:
r1[(r1["elus"]=='UNK') & (r1["koht"]=='UNK')]

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
0,2772,1547,korraldama,,obl,adit,internet,UNK,UNK
2,7834,4571,korraldama,,obl,adit,Pärnu,UNK,UNK
3,15801,9212,korraldama,,obl,adit,tele,UNK,UNK
4,27434,15859,korraldama,,obl,adit,Egiptus,UNK,UNK
5,30447,17704,korraldama,,obl,adit,Edinburgh,UNK,UNK
...,...,...,...,...,...,...,...,...,...
6791,29213349,19639453,korraldama,,obl,adit,msn,UNK,UNK
6792,29230774,19675970,korraldama,,obl,adit,priva,UNK,UNK
6793,29318636,19857849,korraldama,,obl,adit,baar,UNK,UNK
6795,29923267,21100738,korraldama,,obl,adit,noortekas,UNK,UNK
6796,29972527,21203352,korraldama,,obl,adit,tutvum,UNK,UNK

# otsida koondkorpusest välja laused enamuselt koht

### näited kohtadest

In [89]:
collection[2865].text #garaazh

'“ Korraldasime garaazhis väljamüügi , mis on Ameerikas väga levinud võte , ” jutustab Mari-Ann .'

In [92]:
collection[96136].text #maa (mais???????)

'1997.a. mais korraldas linnavalitsus konkursi Narva 1. ja 4. kooli rekonstrueerimiseks .'

In [95]:
collection[331312].text #kool

'1992. a kevadel korraldasid Kirjandusmuuseumi ja Eesti Keele Instituudi folkloristid Eesti koolides tänapäeva õpilasfolkloori kogumise võistluse , mis tõi arhiivi väga suure hulga ( ligi 27 000 lk. ) uut materjali , sh. ligi 3200 “ tavaliste ” mõistatuste teksti ja ligikaudu 25 000 mõistatuste “ perifeeriasse ” kuuluvat teksti .'

### näited elusatest

In [96]:
collection[853741].text # organism

'Põhjamaine toit rahuldab harva organismi kroomivajadust , kroom aga korraldab suhkru ainevahetust organismis ja vähendab magusaisu .'

In [97]:
collection[1806676].text # pere

'Kuid kas ükski keskklassi kuuluv eestlane korraldab avaliku sündmuse rasedusest , sünnitusest ja ristsetest oma peres ?'

In [99]:
collection[3956200].text # süda

'Müncheni südames , Marienplatzil , korraldasid võidurõõmsad sakslased läinudreedese avamängu järel rahvapeo , millele polnuks isegi maailmakuulsal Oktoberfestil midagi vastu panna .'

### näited mis pole kumbki

In [100]:
collection[1547].text # internet

'Aastal 2000 korraldas Valeri Kirss internetis Eesti sajandimissi hääletuse .'

In [101]:
collection[9212].text # tele

'Rahanappuse tõttu kadus ETVst tema menusaade “ Ob-la-di , ob-la-da ” , samal ajal aga korraldab teletäht juba asju Soome teles .'

In [102]:
collection[21100738].text # noortekas

'PETS44: äkki noortekas korraldate oma viktoriine'

# võtta konkreetsed näited mõnest elus verbist

####  näited, mis võiks olla enamus ajast elus (kollased punktid)

In [69]:
source3[(source3["root_cnt"]>=100) & (source3["elus_div"]>=0.15) & (source3["elus_div"]<0.3) & (source3["koht_div"]<=0.05)].sort_values(by=["elus_div"])

,verb,verb_compound,kaane,elus_cnt,koht_cnt,root_cnt,elus_div,koht_div,kaane2
2849,siduma,,el,19,4,126,0.150794,0.031746,seest
1703,valima,välja,el,35,8,231,0.151515,0.034632,seest
1614,kuulutama,,el,37,11,244,0.151639,0.045082,seest
1310,järgnema,,el,46,14,303,0.151815,0.046205,seest
2858,jääma,alla,el,19,4,125,0.152000,0.032000,seest
...,...,...,...,...,...,...,...,...,...
498,piisama,,all,232,38,786,0.295165,0.048346,alale
1964,süüdistama,,el,58,6,196,0.295918,0.030612,seest
86,küsima,,abl,795,43,2681,0.296531,0.016039,alalt
1772,pälvima,,abl,66,6,222,0.297297,0.027027,alalt
1952,rõhutama,,all,59,5,197,0.299492,0.025381,alale

### võtame nt küsima + abl

võtta 2-3 näidet lausetest
- kus on koht
- kus on elus
- kus ei ole elus/koht otsust

- vaja saada kätte transaction_head sentence_id

- transaction head join transaction on head_id
- transaction deprel+kääne tingimus

In [70]:
query = """
SELECT 
distinct 
    head.id as head_id,
    head.sentence_id as sentence_id,
    head.verb,
    head.verb_compound as verb_compound,
    --head.loc as verb_loc,
    --tr.loc as root_loc,
    tr.deprel as root_deprel,
    'abl' as kaane,
    tr.lemma as root_lemma,
    tr.koht as koht,
    tr.elus as elus
    
from 
(select *
from transaction_v2
where deprel = 'obl'
and INSTR(',' || feats || ',', ',' || 'abl' || ',') > 0) as tr

join 

(select * from
v33.transaction_head
where 
verb == 'küsima'
and verb_compound == '') as head

on head.id = tr.head_id

"""

r1 = pd.read_sql_query(query, con)
r1

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
0,1053,595,küsima,,obl,abl,kaart,UNK,UNK
1,2878,1615,küsima,,obl,abl,mina,UNK,YES
2,3956,2302,küsima,,obl,abl,ise,UNK,UNK
3,4240,2511,küsima,,obl,abl,teineteise,UNK,UNK
4,11575,6671,küsima,,obl,abl,füsioterapeut,UNK,YES
...,...,...,...,...,...,...,...,...,...
11844,30070578,21406748,küsima,,obl,abl,HELEN,UNK,UNK
11845,30074091,21414613,küsima,,obl,abl,teine,UNK,UNK
11846,30074161,21414750,küsima,,obl,abl,mina,UNK,YES
11847,30074163,21414751,küsima,,obl,abl,teine,UNK,UNK
11848,30074730,21415862,küsima,,obl,abl,kes,UNK,UNK

In [77]:
r1[r1["elus"]=='YES']

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
1,2878,1615,küsima,,obl,abl,mina,UNK,YES
4,11575,6671,küsima,,obl,abl,füsioterapeut,UNK,YES
7,17242,10050,küsima,,obl,abl,mina,UNK,YES
9,17906,10478,küsima,,obl,abl,isa,UNK,YES
11,20708,12024,küsima,,obl,abl,mina,UNK,YES
...,...,...,...,...,...,...,...,...,...
11832,30058564,21381349,küsima,,obl,abl,sina,UNK,YES
11835,30060611,21385199,küsima,,obl,abl,arst,UNK,YES
11836,30061974,21388592,küsima,,obl,abl,sina,UNK,YES
11841,30066328,21397893,küsima,,obl,abl,mina,UNK,YES
11846,30074161,21414750,küsima,,obl,abl,mina,UNK,YES

In [71]:
r1[r1["koht"]=='YES']

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
96,154682,91379,küsima,,obl,abl,keskus,YES,UNK
130,239559,143660,küsima,,obl,abl,riik,YES,UNK
192,416212,263692,küsima,,obl,abl,riik,YES,UNK
253,633451,407091,küsima,,obl,abl,Katus,YES,UNK
343,898087,567638,küsima,,obl,abl,voodi,YES,UNK
...,...,...,...,...,...,...,...,...,...
11163,27841659,18366199,küsima,,obl,abl,riik,YES,UNK
11273,28158904,18610305,küsima,,obl,abl,välismaa,YES,UNK
11359,28494068,18867750,küsima,,obl,abl,riik,YES,UNK
11374,28522445,18886340,küsima,,obl,abl,Kallas,YES,UNK
11485,28835191,19112689,küsima,,obl,abl,osakond,YES,UNK

In [81]:
r1[(r1["elus"]=='UNK') & (r1["koht"]=='UNK')].head(20)

,head_id,sentence_id,verb,verb_compound,root_deprel,kaane,root_lemma,koht,elus
0,1053,595,küsima,,obl,abl,kaart,UNK,UNK
2,3956,2302,küsima,,obl,abl,ise,UNK,UNK
3,4240,2511,küsima,,obl,abl,teineteise,UNK,UNK
5,12634,7360,küsima,,obl,abl,ise,UNK,UNK
6,14389,8377,küsima,,obl,abl,Vahur,UNK,UNK
8,17364,10123,küsima,,obl,abl,Ülo,UNK,UNK
10,19646,11474,küsima,,obl,abl,keegi,UNK,UNK
13,25656,14810,küsima,,obl,abl,poja,UNK,UNK
15,26021,15029,küsima,,obl,abl,ise,UNK,UNK
17,30630,17830,küsima,,obl,abl,tema,UNK,UNK
18,30689,17863,küsima,,obl,abl,tema,UNK,UNK
20,33532,19440,küsima,,obl,abl,Kristina,UNK,UNK
21,36629,21358,küsima,,obl,abl,tema,UNK,UNK
23,38189,22182,küsima,,obl,abl,Üllar,UNK,UNK
25,39979,23216,küsima,,obl,abl,Liisi,UNK,UNK
28,49453,28791,küsima,,obl,abl,ise,UNK,UNK
29,49590,28869,küsima,,obl,abl,ise,UNK,UNK
31,53147,30991,küsima,,obl,abl,Joala,UNK,UNK
32,53170,31005,küsima,,obl,abl,Joala,UNK,UNK
33,54315,31645,küsima,,obl,abl,vili,UNK,UNK

## otsida koondkorpusest välja laused

### näited kohtadest

In [73]:
collection[567638].text #voodi

'Kuna istusin veel pesus , siis küsisin voodilt : " Kes või mis ma nüüd olen ?'

In [74]:
collection[18610305].text #välismaa

'Minu arvates on normaalne , et me küsime välismaalt nõu ja abi , aga probleem on selles , millisel tasemel ja tasandil nõu ja abi antakse .'

In [75]:
collection[19112689].text # osakond

'Maaelukomisjon küsis arvamust selle eelnõu kohta juriidiliselt osakonnalt , Eesti Maaviljeluse Instituudi taimekaitse sektorilt , Eesti Põllumajandusülikoolilt , Eesti Põllumajandusülikooli Taimekaitse Instituudit , aktsiaseltsilt Kemira , Eesti Konsulentide Ühingult .'

### näited elusatest

In [76]:
collection[6671].text # füsioterapeut

'Jane küsis samas laagris viibinud hispaania füsioterapeudilt , kas too saaks teda aidata ...'

In [78]:
collection[10478].text # isa

"Ta on nimelt veendunud , et tema eelmised abielud Danny Keough' ja Michael Jacksoniga purunesid seetõttu , et ta ei küsinud isalt luba ."

In [79]:
collection[21414750].text # mina

'Rex: miks kõik minult küsivad kus elan ja mu nime MSN-i'

### näited mis pole kumbki

In [80]:
collection[595].text # kaart

"Võimalik , et ta on Tarot' kaartidelt küsinud , millal investeerida ja millal mitte ."

In [82]:
collection[31645].text # vili

'Savisaar räägib , kuidas Vilja ta südame võitis : “ Tema oli selline nooruke , valge kitliga , vist oli valge müts ka ? ” küsib ta Viljalt .'

In [83]:
collection[14810].text # poja

'Küsisin ka pojalt , mida ta arvab , milliseid väärtusi ma olen püüdnud temasse sisendada .'

In [5]:
source_storage.close()

In [6]:
con.close()