## Creates table for elus and koht phrases

Võtab välja need verbobl fraasid, mis on märgitud kohaks või elusaks nimekirja põhjal.

In [9]:
import sqlite3
import pandas as pd
from tqdm import tqdm
import powerlaw as pwl
from collections import Counter
import matplotlib.pyplot as plt
import numpy as np
import sys
sys.path.append("..")
from common_display import display_db_table

## Configuration

In [2]:
DB_DIR = "../example_data"

# loodavad tabelid
PATTERN_MATCHES_DB = f"{DB_DIR}/pattern_matches.db"

LOCATION_PHRASES = "verbobl_phrases_loc"
ACTOR_PHRASES = "verbobl_phrases_live"

# table for all obl locative case verbs and roots 
TRANSACTIONS_OBL_LOC = "trans_obl_loc"

## Connect to database

In [3]:
con = sqlite3.connect(PATTERN_MATCHES_DB)
cur = con.cursor()

## Workflow

In [6]:
%%time

cur.execute("""DROP TABLE IF EXISTS {table}""".format(table = LOCATION_PHRASES))

cur.execute("""
Create table {new_table} as
SELECT * FROM {tbl1}
where koht = 'YES'
""".format(new_table=LOCATION_PHRASES, tbl1=TRANSACTIONS_OBL_LOC))

CPU times: user 2.14 ms, sys: 2.87 ms, total: 5.01 ms
Wall time: 13.9 ms

In [10]:
display_db_table(con, LOCATION_PHRASES)

,head_id,verb,verb_compound,transaction_id,root_word,root_form,word_deprel,pos,tr_feats,koht,elus,loc_case
0,274,saama,kokku,428,kohvik,kohvikus,obl,S,"com,in,sg",YES,,in
1,295,juhtuma,,458,lennujaam,Lennujaamas,obl,S,"com,in,sg",YES,,in
2,296,jääma,,463,liiklusummik,liiklusummikusse,obl,S,"com,ill,sg",YES,,ill
3,355,kukkuma,alla,572,tuba,toas,obl,S,"com,in,sg",YES,,in
4,356,jooksma,,580,tuba,tuppa,obl,S,"adit,com,sg",YES,,adit

In [11]:
%%time

cur.execute("""DROP TABLE IF EXISTS {table}""".format(table = ACTOR_PHRASES))

cur.execute("""
Create table {new_table} as
SELECT * FROM {tbl1}
where elus = 'YES'
""".format(new_table=ACTOR_PHRASES, tbl1=TRANSACTIONS_OBL_LOC))

CPU times: user 0 ns, sys: 5.11 ms, total: 5.11 ms
Wall time: 9.42 ms

In [12]:
display_db_table(con, ACTOR_PHRASES)

,head_id,verb,verb_compound,transaction_id,root_word,root_form,word_deprel,pos,tr_feats,koht,elus,loc_case
0,10,tulema,,19,sina,sul,obl,P,"ad,sg",,YES,ad
1,11,viilima,,23,juht,juhul,obl,S,"ad,com,sg",,YES,ad
2,56,meeldima,,92,mina,Mulle,obl,P,"all,sg",,YES,all
3,85,kirjutama,,131,bänd,bändidele,obl,S,"all,com,pl",,YES,all
4,92,tekkima,,138,mina,mul,obl,P,"ad,sg",,YES,ad

In [13]:
con.close()