## Creating negation tables

Creating a new database with two verb negation tables. The tables will be created from transactions (v32), where the main verb occurs in a negated form. Resulting tables include selected attributes from *transaction_head* and *transaction_row* tables that will be used in creating negation patterns.

In [1]:
import sys
sys.path.append('../../../common_code')

In [2]:
import sqlite3
from paths import PATH_ROOT
from db_operations.verb_transactions.neg_tables_creation import *
from db_operations.db_display import *

## Input parameters

In [3]:
INPUT_DIR = "C:/Users/liivas/Documents/Töö/verbirektisoonid"

RESULT_DB = "neg_tables.db"
TRANSACTION_DB = f"{INPUT_DIR}/v32_data.db"

## Data processing

In [4]:
con = sqlite3.connect(RESULT_DB)
cur = con.cursor()

cur.execute(f'ATTACH DATABASE "{TRANSACTION_DB}" AS transactions')

create_neg_tables(
    cur,
    transaction_head='transactions.transaction_head',
    transaction_row='transactions.transaction_row'
    )
con.close()

## Result

In [7]:
display_sqlite_as_dataframe(RESULT_DB, 'verb_neg', 10)

,id,verb,verb_compound,form,deprel,feats
0,54,saama,,saa,root,"aux,indic,neg,pres,ps"
1,60,tahtma,,taha,conj,"imper,main,neg,pres,ps,ps2,sg"
2,63,õpetama,,õpetanud,conj,"impf,indic,mod,neg,ps"
3,74,saama,,saa,advcl,"imper,mod,neg,pres,ps,ps2,sg"
4,82,pidama,,peaks,aux,"aux,cond,neg,pres,ps"
5,97,võtma,,võta,acl:relcl,"aux,indic,neg,pres,ps"
6,101,oskama,,oska,advcl,"aux,indic,neg,pres,ps"
7,120,pidama,,peaks,aux,"cond,main,neg,pres,ps"
8,121,minema,ära,läheks,conj,"aux,cond,neg,pres,ps"
9,148,tundma,,tunne,advcl,"imper,mod,neg,pres,ps,ps2,sg"

In [8]:
display_sqlite_as_dataframe(RESULT_DB, 'verb_neg_phrases', 10)

,head_id,loc,loc_rel,deprel,form,lemma,feats,parent_loc,pos
0,54,3,-2,xcomp,rikkaks,rikas,"pos,sg,tr",None,A
1,54,4,-1,aux,ei,ei,"aux,neg",None,V
2,60,10,-2,nsubj,nemad,tema,"nom,pl",None,P
3,60,11,-1,aux,ei,ei,"aux,neg",None,V
4,60,13,1,xcomp,olla,olema,"inf,main",None,V
5,60,14,2,xcomp,bussijuhid,bussijuht,"com,nom,pl",None,S
6,63,7,-2,nsubj,ebastabiilsus,ebastabiilsus,"com,nom,sg",None,S
7,63,8,-1,aux,on,olema,"af,aux,indic,pl,pres,ps,ps3",None,V
8,63,12,1,xcomp,elama,elama,"ill,mod,ps,sup",None,V
9,74,2,-2,nsubj,sa,sina,"nom,sg",None,P

## Additional documentation

In [3]:
?create_neg_tables