In [7]:
import sqlite3
import pandas as pd
from tqdm import tqdm
import time

In [2]:
#stat1 = pd.read_csv("transactions_verbs_obl_kohakaandes_patterns_stats_v1.csv",sep=",", encoding="utf-8")
stat2 = pd.read_csv("transactions_verbs_obl_kohakaandes_patterns_stats_v2.csv",sep=",", encoding="utf-8")

In [3]:
stat2 = stat2.sort_values('pat_count', ascending=False)

In [55]:
stat2_2 = stat2.drop(["pat_count"], axis=1)

In [56]:
stat2_2

,root,opteerima,korrigeerima,affima,puhkama,eitama,saaxima,saukima,haugatama,trahvima,...,propageerima,jääma,voolama,pilutama,teisendama,krissuma,töusnuma,käima,ammuma,meilima
50953,aeg,0,0,0,1,1,0,0,0,1,...,1,1,1,0,0,0,0,1,0,0
21500,aasta,1,1,0,1,1,0,0,0,1,...,1,1,1,0,0,0,0,1,0,1
30192,sõna,0,1,0,1,1,0,0,0,1,...,1,1,1,0,0,0,0,1,0,0
51095,mina,0,0,0,1,1,1,0,0,0,...,1,1,1,0,0,0,0,1,0,1
17567,tema,0,1,0,1,1,0,0,0,1,...,0,1,1,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15767,tööhöiveamet,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35150,TAAS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35149,traadipea,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35148,kenadus,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
27551,kvartalikahjum,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
stat2

,root,opteerima,korrigeerima,affima,puhkama,eitama,saaxima,saukima,haugatama,trahvima,...,jääma,voolama,pilutama,teisendama,krissuma,töusnuma,käima,ammuma,meilima,pat_count
50953,aeg,0,0,0,1,1,0,0,0,1,...,1,1,0,0,0,0,1,0,0,1697
21500,aasta,1,1,0,1,1,0,0,0,1,...,1,1,0,0,0,0,1,0,1,1686
30192,sõna,0,1,0,1,1,0,0,0,1,...,1,1,0,0,0,0,1,0,0,1561
51095,mina,0,0,0,1,1,1,0,0,0,...,1,1,0,0,0,0,1,0,1,1547
17567,tema,0,1,0,1,1,0,0,0,1,...,1,1,0,0,0,0,1,0,1,1426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15767,tööhöiveamet,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
35150,TAAS,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
35149,traadipea,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
35148,kenadus,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
27551,kvartalikahjum,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# collection (S): set(root+selle alla kuuluvad mustrid) * number_of_roots
# m: setide arv collectionis
# union of S = universe

In [5]:
mustrid = list(stat2.columns)[1:-1]  # universe

In [6]:
roots = list(stat2["root"])

In [66]:
subsets1 = {}

for i in tqdm(range(len(stat2_2))):
    root = stat2_2.iloc[i]["root"]
    row = stat2_2[stat2_2["root"]==root]
    col = (row == 1).any()
    d = dict(col)
    pats = []
    for k in d.keys():
        if d[k]==True:
            pats.append(k)
    subsets1[root] = pats

100%|█████████████████████████████████████| 55103/55103 [36:40<00:00, 25.04it/s]

In [156]:
len(subsets1)

55103

In [86]:
# numbrite asemel on verbid, siis määrata igale verbile number

verb_to_num = {}
num_to_verb = {}

for i,e in enumerate(mustrid):
    verb_to_num[e] = i+1
    num_to_verb[i+1] = e

In [87]:
# teha subsets2 kus verbide asemel on igas setis numbrid

subsets2 = {}

for k in tqdm(subsets1.keys()):
    values = subsets1[k]
    values2 = [verb_to_num[v] for v in values]
    subsets2[k] = values2

100%|█████████████████████████████████| 55103/55103 [00:00<00:00, 303199.98it/s]

In [73]:
#keys = list(subsets2.keys())[:3]
#subsets2[keys[0]]

Set cover koodi alus

https://github.com/AndreaRubbi/Set-Cover-problem-solution-Python/blob/master/SetCover.pdf

https://github.com/AndreaRubbi/Set-Cover-problem-solution-Python/blob/master/Greedy.py

__author__ = "Andrea Rubbi"

In [150]:
def set_cover(universe, subsets,costs):
    cost=0
    elements = set(e for s in subsets for e in s)
    
    sorted_elements = sorted(elements)
    sorted_universe = sorted(universe)
    
    print(len(elements), len(universe), sorted_elements==sorted_universe)
    
    if sorted_elements != sorted_universe:
        return None
    covered = set()
    cover = []
    sorted_covered = sorted(covered)
    
    #print(len(sorted_covered), )
    
    while sorted_covered != sorted_elements:
        subset = max(subsets, key=lambda s: len(s - covered)/costs[subsets.index(s)])
        cover.append(subset)
        cost+=costs[subsets.index(subset)]
        covered |= subset
        sorted_covered = sorted(covered)
        
        print(len(sorted_covered), len(sorted_elements))
 
    return cover, cost

In [138]:
def main(a,b,c,d, x=time.time()):
    m= a
    universe = d
    sub = b  
    
    subsets = [set(x) for x in sub]
    costs =  c 
    cover = set_cover(universe, subsets,costs)
    #print('covering sets= ',cover[0],'\n',
    #      'cost= ',cover[1],'$')
    print('time: ',time.time()-x)
    
    return cover[0]

### testida 10 setiga aega

In [131]:
S1 = [subsets2[k] for k in subsets2.keys()][:10]
uni = list(set([e for s in S1 for e in s]))
m1 = max(uni)

P1 = [1]*len(S1) # anda igale setile cost(weight) 1

In [139]:
%%time

if __name__ == '__main__':
    covering_sets = main(m1,S1,P1,uni)

2914 2914 True
time:  3.024367332458496
CPU times: user 13.8 ms, sys: 0 ns, total: 13.8 ms
Wall time: 13.2 ms

In [141]:
len(covering_sets)

10

In [144]:
covering_roots = []

for cov_set in covering_sets:
    for k in subsets2.keys():
        subset = sorted(subsets2[k])
        if subset == sorted(cov_set):
            covering_roots.append(k)

In [145]:
covering_roots

['aeg',
 'mina',
 'aasta',
 'sõna',
 'tema',
 'see',
 'mis',
 'päev',
 'algus',
 'Eesti']

### kõik originaal setid

In [151]:
#m1 = max(num_to_verb.keys())
#S1 = [subsets1[k] for k in subsets1.keys()]
#P1 = [1]*len(S1) # anda igale setile cost(weight) 1
#uni = list(verb_to_num.keys())

S1 = [subsets2[k] for k in subsets2.keys()]
uni = list(set([e for s in S1 for e in s]))
m1 = max(uni)

P1 = [1]*len(S1) # anda igale setile cost(weight) 1

In [152]:
%%time

if __name__ == '__main__':
    covering_sets = main(m1,S1,P1,uni)

4066 4066 True
1697 4066
2175 4066
2466 4066
2600 4066
2713 4066
2796 4066
2860 4066
2920 4066
2957 4066
2993 4066
3021 4066
3044 4066
3066 4066
3085 4066
3103 4066
3119 4066
3133 4066
3147 4066
3161 4066
3174 4066
3187 4066
3200 4066
3211 4066
3222 4066
3232 4066
3242 4066
3252 4066
3261 4066
3270 4066
3279 4066
3288 4066
3296 4066
3304 4066
3311 4066
3318 4066
3324 4066
3330 4066
3336 4066
3342 4066
3348 4066
3354 4066
3360 4066
3366 4066
3371 4066
3376 4066
3381 4066
3386 4066
3391 4066
3396 4066
3401 4066
3406 4066
3411 4066
3416 4066
3421 4066
3425 4066
3429 4066
3433 4066
3437 4066
3441 4066
3445 4066
3449 4066
3453 4066
3457 4066
3461 4066
3465 4066
3469 4066
3473 4066
3476 4066
3479 4066
3482 4066
3485 4066
3488 4066
3491 4066
3494 4066
3497 4066
3500 4066
3503 4066
3506 4066
3509 4066
3512 4066
3515 4066
3518 4066
3521 4066
3524 4066
3527 4066
3530 4066
3533 4066
3536 4066
3539 4066
3542 4066
3545 4066
3548 4066
3551 4066
3553 4066
3555 4066
3557 4066
3559 4066
3561 4066
3563 4066
3565 4066
3567 4066
3569 4066
3571 4066
3573 4066
3575 4066
3577 4066
3579 4066
3581 4066
3583 4066
3585 4066
3587 4066
3589 4066
3591 4066
3593 4066
3595 4066
3597 4066
3599 4066
3601 4066
3603 4066
3605 4066
3607 4066
3609 4066
3611 4066
3613 4066
3615 4066
3617 4066
3619 4066
3621 4066
3623 4066
3625 4066
3627 4066
3629 4066
3631 4066
3633 4066
3635 4066
3637 4066
3639 4066
3641 4066
3643 4066
3645 4066
3647 4066
3649 4066
3651 4066
3653 4066
3655 4066
3657 4066
3659 4066
3661 4066
3663 4066
3665 4066
3667 4066
3669 4066
3671 4066
3673 4066
3675 4066
3677 4066
3679 4066
3681 4066
3683 4066
3685 4066
3687 4066
3689 4066
3691 4066
3693 4066
3695 4066
3697 4066
3699 4066
3700 4066
3701 4066
3702 4066
3703 4066
3704 4066
3705 4066
3706 4066
3707 4066
3708 4066
3709 4066
3710 4066
3711 4066
3712 4066
3713 4066
3714 4066
3715 4066
3716 4066
3717 4066
3718 4066
3719 4066
3720 4066
3721 4066
3722 4066
3723 4066
3724 4066
3725 4066
3726 4066
3727 4066
3728 4066
3729 4066
3730 4066
3731 4066
3732 4066
3733 4066
3734 4066
3735 4066
3736 4066
3737 4066
3738 4066
3739 4066
3740 4066
3741 4066
3742 4066
3743 4066
3744 4066
3745 4066
3746 4066
3747 4066
3748 4066
3749 4066
3750 4066
3751 4066
3752 4066
3753 4066
3754 4066
3755 4066
3756 4066
3757 4066
3758 4066
3759 4066
3760 4066
3761 4066
3762 4066
3763 4066
3764 4066
3765 4066
3766 4066
3767 4066
3768 4066
3769 4066
3770 4066
3771 4066
3772 4066
3773 4066
3774 4066
3775 4066
3776 4066
3777 4066
3778 4066
3779 4066
3780 4066
3781 4066
3782 4066
3783 4066
3784 4066
3785 4066
3786 4066
3787 4066
3788 4066
3789 4066
3790 4066
3791 4066
3792 4066
3793 4066
3794 4066
3795 4066
3796 4066
3797 4066
3798 4066
3799 4066
3800 4066
3801 4066
3802 4066
3803 4066
3804 4066
3805 4066
3806 4066
3807 4066
3808 4066
3809 4066
3810 4066
3811 4066
3812 4066
3813 4066
3814 4066
3815 4066
3816 4066
3817 4066
3818 4066
3819 4066
3820 4066
3821 4066
3822 4066
3823 4066
3824 4066
3825 4066
3826 4066
3827 4066
3828 4066
3829 4066
3830 4066
3831 4066
3832 4066
3833 4066
3834 4066
3835 4066
3836 4066
3837 4066
3838 4066
3839 4066
3840 4066
3841 4066
3842 4066
3843 4066
3844 4066
3845 4066
3846 4066
3847 4066
3848 4066
3849 4066
3850 4066
3851 4066
3852 4066
3853 4066
3854 4066
3855 4066
3856 4066
3857 4066
3858 4066
3859 4066
3860 4066
3861 4066
3862 4066
3863 4066
3864 4066
3865 4066
3866 4066
3867 4066
3868 4066
3869 4066
3870 4066
3871 4066
3872 4066
3873 4066
3874 4066
3875 4066
3876 4066
3877 4066
3878 4066
3879 4066
3880 4066
3881 4066
3882 4066
3883 4066
3884 4066
3885 4066
3886 4066
3887 4066
3888 4066
3889 4066
3890 4066
3891 4066
3892 4066
3893 4066
3894 4066
3895 4066
3896 4066
3897 4066
3898 4066
3899 4066
3900 4066
3901 4066
3902 4066
3903 4066
3904 4066
3905 4066
3906 4066
3907 4066
3908 4066
3909 4066
3910 4066
3911 4066
3912 4066
3913 4066
3914 4066
3915 4066
3916 4066
3917 4066
3918 4066
3919 4066
3920 4066
3921 4066
3922 4066
3923 4066
3924 4066
3925 4066
3926 4066
3927 4066
3928 4066
3929 4066
3930 4066
3931 4066
3932 4066
3933 4066
3934 4066
3935 4066
3936 4066
3937 4066
3938 4066
3939 4066
3940 4066
3941 4066
3942 4066
3943 4066
3944 4066
3945 4066
3946 4066
3947 4066
3948 4066
3949 4066
3950 4066
3951 4066
3952 4066
3953 4066
3954 4066
3955 4066
3956 4066
3957 4066
3958 4066
3959 4066
3960 4066
3961 4066
3962 4066
3963 4066
3964 4066
3965 4066
3966 4066
3967 4066
3968 4066
3969 4066
3970 4066
3971 4066
3972 4066
3973 4066
3974 4066
3975 4066
3976 4066
3977 4066
3978 4066
3979 4066
3980 4066
3981 4066
3982 4066
3983 4066
3984 4066
3985 4066
3986 4066
3987 4066
3988 4066
3989 4066
3990 4066
3991 4066
3992 4066
3993 4066
3994 4066
3995 4066
3996 4066
3997 4066
3998 4066
3999 4066
4000 4066
4001 4066
4002 4066
4003 4066
4004 4066
4005 4066
4006 4066
4007 4066
4008 4066
4009 4066
4010 4066
4011 4066
4012 4066
4013 4066
4014 4066
4015 4066
4016 4066
4017 4066
4018 4066
4019 4066
4020 4066
4021 4066
4022 4066
4023 4066
4024 4066
4025 4066
4026 4066
4027 4066
4028 4066
4029 4066
4030 4066
4031 4066
4032 4066
4033 4066
4034 4066
4035 4066
4036 4066
4037 4066
4038 4066
4039 4066
4040 4066
4041 4066
4042 4066
4043 4066
4044 4066
4045 4066
4046 4066
4047 4066
4048 4066
4049 4066
4050 4066
4051 4066
4052 4066
4053 4066
4054 4066
4055 4066
4056 4066
4057 4066
4058 4066
4059 4066
4060 4066
4061 4066
4062 4066
4063 4066
4064 4066
4065 4066
4066 4066
time:  18151.462626218796
CPU times: user 4h 16min 28s, sys: 1.77 s, total: 4h 16min 30s
Wall time: 4h 16min 32s

In [153]:
len(covering_sets)

534

In [154]:
covering_roots = []

for cov_set in covering_sets:
    for k in subsets2.keys():
        subset = sorted(subsets2[k])
        if subset == sorted(cov_set):
            covering_roots.append(k)

In [155]:
len(covering_roots)

536

In [157]:
covering_roots

['aeg',
 'mina',
 'aasta',
 'sõna',
 'tema',
 'see',
 'sina',
 'mis',
 'ise',
 'kodu',
 'hommik',
 'õhtu',
 'hetk',
 'lava',
 'juht',
 'algus',
 'teema',
 'vesi',
 'nurk',
 'tänav',
 'keel',
 'selg',
 'teine',
 'silm',
 'Tallinn',
 'pea',
 'käsi',
 'päev',
 'minut',
 'nägu',
 'põhi',
 'suvi',
 'voodi',
 'määr',
 'suu',
 'kes',
 'maailm',
 'tee',
 'kool',
 'august',
 'ulatus',
 'aken',
 'tasku',
 'maa',
 'mood',
 'saal',
 'alus',
 'tase',
 'rida',
 'õu',
 'arvuti',
 'internet',
 'kõrv',
 'ahi',
 'Eesti',
 'töö',
 'september',
 'auto',
 'öö',
 'ühiskond',
 'aed',
 'baar',
 'stiil',
 'tool',
 'laut',
 'rõõm',
 'plikatartu',
 'lõpp',
 'hinnang',
 'koht',
 'inimene',
 'laupäev',
 'esmaspäev',
 'maja',
 'aprill',
 'november',
 'küsimus',
 'USA',
 'suund',
 'kuju',
 'pind',
 'süda',
 'tagajärg',
 'finaal',
 'põrand',
 'tuul',
 'uni',
 'pudel',
 'priva',
 'pää',
 'sää',
 'päike',
 'laup',
 'andmed',
 'mõte',
 'kord',
 'riik',
 'väide',
 'Tartu',
 'sügis',
 'jaanuar',
 'pool',
 'elu',
 'oktoober',
 'detsember',
 'Euroopa',
 'juuni',
 'nädalavahetus',
 'kohtumine',
 'tuba',
 'alune',
 'tingimus',
 'külg',
 'plats',
 'oma',
 'Pärnu',
 'paik',
 'raamat',
 'tali',
 'iga',
 'ring',
 'pood',
 'eesmärk',
 'meri',
 'teater',
 'üldjuht',
 'saade',
 'laev',
 'ots',
 'kõrgus',
 'leht',
 'kontsert',
 'pilt',
 'hääl',
 'kaugus',
 'tegelikkus',
 'restoran',
 'jooks',
 'koridor',
 'jää',
 'plaat',
 'pink',
 'avalikkus',
 'nahk',
 'värv',
 'aine',
 'kogemus',
 'süli',
 'maal',
 'pihk',
 'muutus',
 'kurk',
 'valu',
 'vaimustus',
 'printsiip',
 'vaip',
 'naer',
 'suits',
 'sitt',
 'viha',
 'Marco',
 'suunurk',
 'kamin',
 'vats',
 'mõnu',
 'mikser',
 'pinu',
 'nädal',
 'linn',
 'kinnitus',
 'osa',
 'mees',
 'Venemaa',
 'pühapäev',
 'märts',
 'teisipäev',
 'põhjus',
 'kuu',
 'ala',
 'koha',
 'piirkond',
 'turg',
 'viis',
 'mai',
 'film',
 'asi',
 'piir',
 'korter',
 'kesklinn',
 'Rootsi',
 'tänapäev',
 'sadam',
 'maantee',
 'MM',
 'pank',
 'vajadus',
 'juhtimine',
 'klubi',
 'taust',
 'mägi',
 'katse',
 'õhk',
 'köök',
 'kirik',
 'kallas',
 'jalg',
 'politsei',
 'rahvas',
 'vorm',
 'sein',
 'grupp',
 'hilisõhtu',
 'poiss',
 'noor',
 'tegemine',
 'liin',
 'Poola',
 'Hiina',
 'Toompea',
 'turniir',
 'kokkulepe',
 'projekt',
 'Suurbritannia',
 'sõber',
 'eelarve',
 'park',
 'keha',
 'lootus',
 'väärtus',
 'kõne',
 'jutt',
 'loodus',
 'tekst',
 'paber',
 'jõgi',
 'põld',
 'Ida-Virumaa',
 'kontor',
 'palve',
 'nimekiri',
 'lääs',
 'järv',
 'liiga',
 'müük',
 'eeskuju',
 'järjekord',
 'number',
 'puu',
 'stuudio',
 'protsent',
 'mängija',
 'eelnõu',
 'äär',
 'arvamus',
 'kultuur',
 'positsioon',
 'kanal',
 'kooskõla',
 'regioon',
 'loom',
 'vaheaeg',
 'sündmus',
 'riigieelarve',
 'organism',
 'võit',
 'AS',
 'kongress',
 'sild',
 'ametikoht',
 'minevik',
 'esimene',
 'MK-etapp',
 'sõjavägi',
 'pimedus',
 'õlg',
 'romaan',
 'lähitulevik',
 'tudeng',
 'veri',
 'foto',
 'objekt',
 'valija',
 'sisu',
 'sündmuskoht',
 'tellimus',
 'mälu',
 'ida',
 'häda',
 'net',
 'mõis',
 'joon',
 'saun',
 'maastik',
 'pöördumine',
 'arve',
 'kaks',
 'veerandaeg',
 'hinge',
 'nina',
 'asend',
 'muu',
 'pubi',
 'vara',
 'laad',
 'väikelinn',
 'lagi',
 'ettevalmistamine',
 'näide',
 'kokkupõrge',
 'rahvus',
 'haige',
 'tagaiste',
 'põõsas',
 'liha',
 'telesaade',
 'kõrgushüpe',
 'põlv',
 'vann',
 'löök',
 'mark',
 'riietusruum',
 'jaht',
 'toll',
 'esik',
 'valge',
 'koor',
 'teleekraan',
 'pealkiri',
 'õlu',
 'pööre',
 'list',
 'prognoos',
 'temperatuur',
 'kuumus',
 'kohtusaal',
 'postkast',
 'keskväljak',
 'kamp',
 'toime',
 'matt',
 'tükk',
 'partii',
 'õismägi',
 'detail',
 'külm',
 'raffa',
 'õnn',
 'lehm',
 'sõbranna',
 'liik',
 'kaitsja',
 'sagedus',
 'klassika',
 'vihm',
 'üksikmäng',
 'võsa',
 'idu',
 'oks',
 'rõivas',
 'muda',
 'vägivald',
 'sünnitusmaja',
 'kulutus',
 'vale',
 'Delfi',
 'tall',
 'institutsioon',
 'kombinatsioon',
 'selline',
 'põleng',
 'televiisor',
 'formaat',
 'garderoob',
 'leib',
 'tallinn',
 'siga',
 'plakat',
 'kohv',
 'kõvaketas',
 'arestikamber',
 'linnaeelarve',
 'aktus',
 'mulla',
 'toomkirik',
 'ämber',
 'kokkupuude',
 'TTÜ',
 'külmik',
 'pealagi',
 'kitarr',
 'volbriöö',
 'silmanurk',
 'segu',
 'alaealine',
 'lukk',
 'taluõu',
 'levi',
 'konstruktsioon',
 'ajapuudus',
 'istumine',
 'viht',
 'kasukas',
 'hüvitusfond',
 'valem',
 'taktika',
 'soon',
 'küünarnukk',
 'vanadus',
 'minumeel',
 'emaplaat',
 'põrm',
 'ärevus',
 'stardirada',
 'tagauks',
 'Mulgimaa',
 'vilu',
 'MEGA',
 'dimensioon',
 'lissa',
 'pulmapäev',
 'kube',
 'ENSV',
 'sõel',
 'aupaiste',
 'toompuiestee',
 'kints',
 'vineer',
 'paljassaar',
 'kiim',
 'latv',
 'pakiruum',
 'veis',
 'kordus',
 'exo',
 'võimatu',
 'ettevaatus',
 'diktofon',
 'mahalaskmine',
 'külmkamber',
 'sünna',
 'idakallas',
 'spämm',
 'kodukasutaja',
 'rahatäht',
 'kõver',
 'say',
 'nokk',
 'yleva',
 'parkett',
 'kolb',
 'näljastreik',
 'elustamine',
 'tarvidus',
 'mega',
 'yxtei',
 'sukkpüksid',
 'digita',
 'isikuandmed',
 'kallistus',
 'teatrilugu',
 'LIRO',
 'soldat',
 'made',
 'seelikusaba',
 'maksvus',
 'ventilaator',
 'sorts',
 'jahilasketiir',
 'Jehoova',
 'sahk',
 'farss',
 'elavdamine',
 'õppesõiduplats',
 'hallukas',
 'parkettpõrand',
 'joobeaste',
 'keg',
 'oll',
 'kiigelaulukuuik',
 'õhtupäike',
 'sarvkest',
 'põlemiskamber',
 'kaabelvõrk',
 'ornament',
 'lepajõgi',
 'heategevusõhtu',
 'džässtrio',
 'artike',
 'homoseksuaalmäng',
 'cumplida',
 'rhodanienne',
 'logimissüsteem',
 'melanž',
 'jahutusseade',
 'järvemaastik',
 'mön',
 'lõpuraund',
 'tSualainni',
 'tSualainn',
 'oie',
 'jarsu',
 'deodorandipudel',
 'paalipere',
 'âgée',
 'kultuurilooline',
 'tsi',
 'pedeportaal',
 'entrepris',
 'S-video',
 'standardlahk',
 'Xedo',
 'Keskaegne',
 'uhe',
 'maneezhiliiv',
 '22.00',
 'regeerimine',
 'Postlingvaalse',
 'parrandamine',
 'concanente',
 'pohjus',
 'nokuhaldjas',
 'tippründaja',
 'neljateist-aasta',
 'jalgpallikunst',
 'pilvenukk',
 'jänkiküla',
 'masinloetav',
 'vastuponnistus',
 'topless-rand',
 'aveugle',
 'välisklaas',
 'haavapalavik',
 'õlipump',
 'ellujääja',
 'narkootikumiotsing',
 'simu']

In [160]:
with open('verb_analysis_kohakaanded_root_mustrid_set_cover_greedy_1_roots.txt', 'w') as f:
    for line in covering_roots:
        f.write(f"{line}\n")

In [159]:
import csv

In [161]:
with open("verb_analysis_kohakaanded_root_mustrid_set_cover_greedy_1_sets.csv", "w") as f:
    wr = csv.writer(f)
    wr.writerows(covering_sets)

In [163]:
import pickle

In [164]:


with open('set_cover_1_verb2num.pkl', 'wb') as f:
    pickle.dump(verb_to_num, f)
        

with open('set_cover_1_num2verb.pkl', 'wb') as f:
    pickle.dump(num_to_verb, f)

In [165]:
with open('set_cover_1_verb2num.pkl', 'rb') as f:
    loaded_dict = pickle.load(f)

print(len(verb_to_num))
print(len(loaded_dict))

4066
4066

In [ ]:
#m1= 5 # maksimaalne väärtus üle setide??
#S1 = [[1,3],[2],[1,2,5],[3,5],[4],[5],[1,3],[2,4,5],[1,2],[2,3]] # setid
#P1 = [11,4,9,12,5,4,13,12,8,9] # mille alusel cost?