# Adding semantic tags to an sqlite table

This notebook adds semantic tags to adverbials in the Estonian Reference corpus. The semantic types are added to two sqlite database tables *spatial_obl* and *advmod* into a new column called *ekilex_tag*.

In [1]:
#imports
import sqlite3
import os
import re

In [2]:
def column_exists(cursor, table, column):
    cursor.execute(f"PRAGMA table_info({table})")
    return any(row[1] == column for row in cursor.fetchall())

In [ ]:
# database file path
DATABASE = "../drive_data/v33_koondkorpus_transaktsioonid_v04_2.db"

NER_TIMEX_DB = "../drive_data/v33_ner_timex_20250922-094340.db"

DB2 = "../drive_data/v33_koondkorpus_transaktsioonid_v05.db"

In [10]:
# connecting with database
conn_db = sqlite3.connect(DATABASE)
cursor_db = conn_db.cursor()

### Save word and semantic type to dict

In [4]:
def word_semtype_fun(directory_str):
    word_semtype = [] # tuples of semtype and word, i.e. (amount, aegsamini)
    
    directory = os.fsencode(directory_str)
    
    for file in os.listdir(directory):
        file_name = os.fsdecode(file)
        filepath = directory_str + '/' + file_name
        semtype = re.findall(r"^(?:adv_)?(.+?)\.[^.]+$", file_name)
        with open(filepath, "r", encoding="utf-8") as f:
            words = f.read().splitlines()
            for word in words:
                word_semtype.append((semtype[0], word))  
    return word_semtype

In [5]:
directory_obl =  "../base_data/v05_wordlists_obl"
word_semtype_obl = word_semtype_fun(directory_obl)

In [6]:
directory_advmod =  "../base_data/v05_wordlists_advmod"
word_semtype_adv = word_semtype_fun(directory_advmod)

In [7]:
word_semtype_adv

[('amount', 'aegsamini'),
 ('amount', 'ainumalt'),
 ('amount', 'ammendavalt'),
 ('amount', 'arvamata'),
 ('amount', 'aupoolest'),
 ('amount', 'aupärast'),
 ('amount', 'enam-vähem'),
 ('amount', 'esimeseks'),
 ('amount', 'esiteks'),
 ('amount', 'etemini'),
 ('amount', 'fantastiliselt'),
 ('amount', 'forsseeritult'),
 ('amount', 'haaravalt'),
 ('amount', 'halvemini'),
 ('amount', 'halvimini'),
 ('amount', 'hambuni'),
 ('amount', 'harvanähtavalt'),
 ('amount', 'hiiglamoodi'),
 ('amount', 'hinge põhjani'),
 ('amount', 'hingepõhjani'),
 ('amount', 'hinge põhjast'),
 ('amount', 'hingepõhjast'),
 ('amount', 'hirmpalju'),
 ('amount', 'hulga'),
 ('amount', 'hulganiselt'),
 ('amount', 'hulgim'),
 ('amount', 'hullu'),
 ('amount', 'hullult'),
 ('amount', 'hullumoodi'),
 ('amount', 'hullupööra'),
 ('amount', 'hullusti'),
 ('amount', 'häbemata'),
 ('amount', 'ilmama'),
 ('amount', 'imeharva'),
 ('amount', 'imehästi'),
 ('amount', 'imevähe'),
 ('amount', 'issanda'),
 ('amount', 'jalaga segada'),
 ('amount', 'jumala'),
 ('amount', 'jumalama'),
 ('amount', 'jumalast'),
 ('amount', 'jumitult'),
 ('amount', 'jupike'),
 ('amount', 'jupikene'),
 ('amount', 'juuksejuurteni'),
 ('amount', 'jõletult'),
 ('amount', 'kaduvvähe'),
 ('amount', 'kaelani'),
 ('amount', 'kardinaalselt'),
 ('amount', 'karvavõrd'),
 ('amount', 'karvavõrdki'),
 ('amount', 'karvavõrra'),
 ('amount', 'karvavõrragi'),
 ('amount', 'karvaväärt'),
 ('amount', 'karvaväärtki'),
 ('amount', 'katkemiseni'),
 ('amount', 'kindlamalt'),
 ('amount', 'kindlamini'),
 ('amount', 'kirjeldamatult'),
 ('amount', 'kolmandaks'),
 ('amount', 'kordselt'),
 ('amount', 'kraadivõrra'),
 ('amount', 'kriipsuvõrd'),
 ('amount', 'kriipsuvõrdki'),
 ('amount', 'kriipsuvõrra'),
 ('amount', 'kriipsuvõrragi'),
 ('amount', 'kröömike'),
 ('amount', 'kröömikene'),
 ('amount', 'kröömikese'),
 ('amount', 'kui palju'),
 ('amount', 'kuipalju'),
 ('amount', 'kuivõrd'),
 ('amount', 'kuivõrra'),
 ('amount', 'kuninglikult'),
 ('amount', 'kuradimoodi'),
 ('amount', 'kuratlikult'),
 ('amount', 'kurjamoodi'),
 ('amount', 'kuuendaks'),
 ('amount', 'kõige enam'),
 ('amount', 'kõige halvemini'),
 ('amount', 'kõige lihtsamini'),
 ('amount', 'kõige lõbusamini'),
 ('amount', 'kõige nõrgemalt'),
 ('amount', 'kõige nõrgemini'),
 ('amount', 'kõige paremini'),
 ('amount', 'kõige rohkem'),
 ('amount', 'kõigest'),
 ('amount', 'kõrgesti'),
 ('amount', 'kõrvuni'),
 ('amount', 'kübeke'),
 ('amount', 'kübekene'),
 ('amount', 'küllaga'),
 ('amount', 'küllaldaselt'),
 ('amount', 'küünevõrd'),
 ('amount', 'küünevõrdki'),
 ('amount', 'küünevõrra'),
 ('amount', 'küünevõrragi'),
 ('amount', 'küüneväärt'),
 ('amount', 'küüneväärtki'),
 ('amount', 'lademes'),
 ('amount', 'lademetes'),
 ('amount', 'ligilähedalt'),
 ('amount', 'lihtsaimini'),
 ('amount', 'lihtsamini'),
 ('amount', 'liiaks'),
 ('amount', 'liialt'),
 ('amount', 'liiast'),
 ('amount', 'liiasti'),
 ('amount', 'liigselt'),
 ('amount', 'loalt'),
 ('amount', 'lollimoodi'),
 ('amount', 'lõbusaimini'),
 ('amount', 'lõbusamalt'),
 ('amount', 'lõbusamini'),
 ('amount', 'lõdvemale'),
 ('amount', 'lõhkemiseni'),
 ('amount', 'lõpmatuseni'),
 ('amount', 'lõpuni'),
 ('amount', 'läbi ja lõhki'),
 ('amount', 'läbi ja läbi'),
 ('amount', 'läbi-lõhki'),
 ('amount', 'läbini'),
 ('amount', 'läbinisti'),
 ('amount', 'maailma'),
 ('amount', 'maailmama'),
 ('amount', 'maksimaalselt'),
 ('amount', 'massiliselt'),
 ('amount', 'megapalju'),
 ('amount', 'mehemoodi'),
 ('amount', 'minimaalselt'),
 ('amount', 'mitmevõrra'),
 ('amount', 'mõnda pidi'),
 ('amount', 'mõndapidi'),
 ('amount', 'mõneti'),
 ('amount', 'mõnevõrra'),
 ('amount', 'mõõdukalt'),
 ('amount', 'mõõtmatult'),
 ('amount', 'mäekõrguselt'),
 ('amount', 'märgatavalt'),
 ('amount', 'märkimisväärselt'),
 ('amount', 'märksa'),
 ('amount', 'määratult'),
 ('amount', 'natike'),
 ('amount', 'natikene'),
 ('amount', 'natsa'),
 ('amount', 'natu'),
 ('amount', 'natuke'),
 ('amount', 'natukene'),
 ('amount', 'natukese'),
 ('amount', 'natu-natuke'),
 ('amount', 'natu-natukene'),
 ('amount', 'neetult'),
 ('amount', 'neljandaks'),
 ('amount', 'niivõrd'),
 ('amount', 'niti-natike'),
 ('amount', 'nõksu'),
 ('amount', 'nõksuke'),
 ('amount', 'nõndapalju'),
 ('amount', 'nõnna'),
 ('amount', 'nõrgalt'),
 ('amount', 'nõrgasti'),
 ('amount', 'nõrgemalt'),
 ('amount', 'nõrgemini'),
 ('amount', 'nõrkemiseni'),
 ('amount', 'nähtavalt'),
 ('amount', 'okeilt'),
 ('amount', 'oluliselt'),
 ('amount', 'orienteerivalt'),
 ('amount', 'orienteeruvalt'),
 ('amount', 'otsatult'),
 ('amount', 'paljuks'),
 ('amount', 'paljuti'),
 ('amount', 'parimini'),
 ('amount', 'peaaegu'),
 ('amount', 'peadpööritavalt'),
 ('amount', 'peagu'),
 ('amount', 'pea jagu'),
 ('amount', 'peajagu'),
 ('amount', 'piiritult'),
 ('amount', 'piisavalt'),
 ('amount', 'pilgel'),
 ('amount', 'pilgeni'),
 ('amount', 'pilkaselt'),
 ('amount', 'pireke'),
 ('amount', 'pisinatuke'),
 ('amount', 'pisut'),
 ('amount', 'pluss-miinus'),
 ('amount', 'pooleldi'),
 ('amount', 'poolenisti'),
 ('amount', 'pooliti'),
 ('amount', 'puha'),
 ('amount', 'puhta'),
 ('amount', 'puhtani'),
 ('amount', 'puhtanisti'),
 ('amount', 'põhjatult'),
 ('amount', 'põrgulikult'),
 ('amount', 'päratult'),
 ('amount', 'pööraselt'),
 ('amount', 'raasike'),
 ('amount', 'raasikene'),
 ('amount', 'raasuke'),
 ('amount', 'rahuldavalt'),
 ('amount', 'raudselt'),
 ('amount', 'rekordpalju'),
 ('amount', 'rekordvähe'),
 ('amount', 'röögatult'),
 ('amount', 'sajakordselt'),
 ('amount', 'sajaprotsendiliselt'),
 ('amount', 'sajuti'),
 ('amount', 'samajagu'),
 ('amount', 'samapalju'),
 ('amount', 'samavõrd'),
 ('amount', 'samavõrra'),
 ('amount', 'seamoodi'),
 ('amount', 'sedajagu'),
 ('amount', 'sedavõrd'),
 ('amount', 'seevõrd'),
 ('amount', 'seevõrra'),
 ('amount', 'sellejagu'),
 ('amount', 'sellevõrra'),
 ('amount', 'setugi'),
 ('amount', 'setupalju'),
 ('amount', 'silmini'),
 ('amount', 'sugupärast'),
 ('amount', 'suht-koht'),
 ('amount', 'suhtkoht'),
 ('amount', 'suisasui'),
 ('amount', 'surmani'),
 ('amount', 'surmkindlalt'),
 ('amount', 'suti'),
 ('amount', 'sutike'),
 ('amount', 'sutikene'),
 ('amount', 'sutsu'),
 ('amount', 'sutsuke'),
 ('amount', 'sutsukene'),
 ('amount', 'sutt-sutt'),
 ('amount', 'suuremat'),
 ('amount', 'suurt'),
 ('amount', 'sõnulseletamatult'),
 ('amount', 'südame põhjani'),
 ('amount', 'südamepõhjani'),
 ('amount', 'südame põhjast'),
 ('amount', 'südamepõhjast'),
 ('amount', 'teiseks'),
 ('amount', 'terveni'),
 ('amount', 'tervenisti'),
 ('amount', 'tibake'),
 ('amount', 'tibakene'),
 ('amount', 'tilgatult'),
 ('amount', 'tilgatumaks'),
 ('amount', 'tilgatumalt'),
 ('amount', 'tohutult'),
 ('amount', 'totaalselt'),
 ('amount', 'tsipa'),
 ('amount', 'tsipake'),
 ('amount', 'tsipakene'),
 ('amount', 'tsuti'),
 ('amount', 'tsutike'),
 ('amount', 'tsutikene'),
 ('amount', 'tsutt'),
 ('amount', 'tuhandekordselt'),
 ('amount', 'tulvil'),
 ('amount', 'tundmatuseni'),
 ('amount', 'tunduvalt'),
 ('amount', 'tuntavalt'),
 ('amount', 'tuuris'),
 ('amount', 'tõsitsi'),
 ('amount', 'täielikult'),
 ('amount', 'täieliselt'),
 ('amount', 'täielt'),
 ('amount', 'täienisti'),
 ('amount', 'täiesti'),
 ('amount', 'tüki'),
 ('amount', 'umbes-täpselt'),
 ('amount', 'umbestäpselt'),
 ('amount', 'uskumatuseni'),
 ('amount', 'valdavalt'),
 ('amount', 'valikuliselt'),
 ('amount', 'valjemalt'),
 ('amount', 'valjemini'),
 ('amount', 'varglikult'),
 ('amount', 'vargselt'),
 ('amount', 'veelgi'),
 ('amount', 'veidi'),
 ('amount', 'veidike'),
 ('amount', 'veidikene'),
 ('amount', 'veidikese'),
 ('amount', 'veits'),
 ('amount', 'viiendaks'),
 ('amount', 'viimseni'),
 ('amount', 'vilamisi'),
 ('amount', 'vilksamisi'),
 ('amount', 'volilt'),
 ('amount', 'võimatult'),
 ('amount', 'võrreldamatult'),
 ('amount', 'väga'),
 ('amount', 'vähe'),
 ('amount', 'vähegi'),
 ('amount', 'väheke'),
 ('amount', 'vähekene'),
 ('amount', 'vähekese'),
 ('amount', 'ärarääkimata'),
 ('amount', 'äratundmatuseni'),
 ('amount', 'äraütlemata'),
 ('amount', 'äärepealt'),
 ('amount', 'ääretult'),
 ('amount', 'äärmiselt'),
 ('amount', 'öeldamatult'),
 ('amount', 'üdini'),
 ('amount', 'ühepalju'),
 ('amount', 'ühevõrra'),
 ('amount', 'ülearu'),
 ('amount', 'ülearuselt'),
 ('amount', 'üle jõu käivalt'),
 ('amount', 'ülejõukäivalt'),
 ('amount', 'ülekaalukalt'),
 ('amount', 'üleliia'),
 ('amount', 'üleliiga'),
 ('amount', 'üleliigselt'),
 ('amount', 'ülemäära'),
 ('amount', 'ülemääraselt'),
 ('amount', 'üleni'),
 ('amount', 'ülepakutult'),
 ('amount', 'ülepea'),
 ('amount', 'ülepingutatult'),
 ('amount', 'üleprahi'),
 ('amount', 'ülimalt'),
 ('amount', 'ülipalju'),
 ('amount', 'üliväga'),
 ('amount', 'ütlemata'),
 ('amount', 'üüratult'),
 ('amount', 'rohkem'),
 ('amount', 'palju'),
 ('amount', 'vähem'),
 ('amount', 'eriti'),
 ('manner', 'a cappella'),
 ('manner', 'accelerando'),
 ('manner', 'ad libitum'),
 ('manner', 'administratiivkorras'),
 ('manner', 'afekteeritult'),
 ('manner', 'agaralt'),
 ('manner', 'agarasti'),
 ('manner', 'agitato'),
 ('manner', 'ahastavalt'),
 ('manner', 'ahistavalt'),
 ('manner', 'ahnelt'),
 ('manner', 'ahnesti'),
 ('manner', 'ahtalt'),
 ('manner', 'aimamisi'),
 ('manner', 'aineliselt'),
 ('manner', 'aineti'),
 ('manner', 'ainiti'),
 ('manner', 'ainitiselt'),
 ('manner', 'ainuisikuliselt'),
 ('manner', 'ainuti'),
 ('manner', 'ajatasa'),
 ('manner', 'ajuga'),
 ('manner', 'aka'),
 ('manner', 'akromaatiliselt'),
 ('manner', 'akuraatselt'),
 ('manner', 'alistunult'),
 ('manner', 'alkeemiliselt'),
 ('manner', 'allargando'),
 ('manner', 'althõlma'),
 ('manner', 'altkulmu'),
 ('manner', 'altkäe'),
 ('manner', 'altpulga'),
 ('manner', 'amabile'),
 ('manner', 'ammuli sui'),
 ('manner', 'ammulisui'),
 ('manner', 'analoogiliselt'),
 ('manner', 'analoogselt'),
 ('manner', 'angroo'),
 ('manner', 'animato'),
 ('manner', 'anuvalt'),
 ('manner', 'aplalt'),
 ('manner', 'aplamisi'),
 ('manner', 'aplasti'),
 ('manner', 'a posteriori'),
 ('manner', 'appassionato'),
 ('manner', 'a priori'),
 ('manner', 'aralt'),
 ('manner', 'ardente'),
 ('manner', 'areldi'),
 ('manner', 'argipäevaselt'),
 ('manner', 'arglikult'),
 ('manner', 'argselt'),
 ('manner', 'argsi'),
 ('manner', 'argumenteeritult'),
 ('manner', 'arhitektuuriliselt'),
 ('manner', 'aristokraatlikult'),
 ('manner', 'aristokraatselt'),
 ('manner', 'armastavalt'),
 ('manner', 'armsalt'),
 ('manner', 'armsasti'),
 ('manner', 'armutult'),
 ('manner', 'aromaatselt'),
 ('manner', 'arrogantselt'),
 ('manner', 'arvamisi'),
 ('manner', 'arvustavalt'),
 ('manner', 'asap'),
 ('manner', 'asjatult'),
 ('manner', 'aste-astmelt'),
 ('manner', 'astmeti'),
 ('manner', 'astroloogiliselt'),
 ('manner', 'a tempo'),
 ('manner', 'atraktiivselt'),
 ('manner', 'auga'),
 ('manner', 'aukus'),
 ('manner', 'au naturel'),
 ('manner', 'avakõrvu'),
 ('manner', 'avakäsi'),
 ('manner', 'avalikult'),
 ('manner', 'avamatult'),
 ('manner', 'avameeli'),
 ('manner', 'avameelselt'),
 ('manner', 'avasilmi'),
 ('manner', 'avasui'),
 ('manner', 'avasüli'),
 ('manner', 'bel canto'),
 ('manner', 'bioloogiliselt'),
 ('manner', 'bukvaalselt'),
 ('manner', 'calando'),
 ('manner', 'cantabile'),
 ('manner', 'cito'),
 ('manner', 'comodo'),
 ('manner', 'cum laude'),
 ('manner', 'decrescendo'),
 ('manner', 'de facto'),
 ('manner', 'de iure'),
 ('manner', 'dekoratiivselt'),
 ('manner', 'delikaatselt'),
 ('manner', 'dementselt'),
 ('manner', 'demonstratiivselt'),
 ('manner', 'de profundis'),
 ('manner', 'detailselt'),
 ('manner', 'diakrooniliselt'),
 ('manner', 'diferentseeritult'),
 ('manner', 'digitaalselt'),
 ('manner', 'diktaatorlikult'),
 ('manner', 'diplomaatiliselt'),
 ('manner', 'distsiplineeritult'),
 ('manner', 'dolce'),
 ('manner', 'doloroso'),
 ('manner', 'dotseerivalt'),
 ('manner', 'ebaedukalt'),
 ('manner', 'ebaotstarbekalt'),
 ('manner', 'ebaseaduslikult'),
 ('manner', 'ebasündsalt'),
 ('manner', 'ebateadlikult'),
 ('manner', 'ebatõeliselt'),
 ('manner', 'ebaõigesti'),
 ('manner', 'edasilükkamatult'),
 ('manner', 'edevalt'),
 ('manner', 'edutult'),
 ('manner', 'eesmärgikindlalt'),
 ('manner', 'eesmärgitult'),
 ('manner', 'eestimaiselt'),
 ('manner', 'eestipäraselt'),
 ('manner', 'ehkupeale'),
 ('manner', 'eksikombel'),
 ('manner', 'eksimatult'),
 ('manner', 'eksklusiivselt'),
 ('manner', 'eksponentsiaalselt'),
 ('manner', 'elamuslikult'),
 ('manner', 'elavalt'),
 ('manner', 'elektrooniliselt'),
 ('manner', 'elektroonselt'),
 ('manner', 'eluga'),
 ('manner', 'eluohtlikult'),
 ('manner', 'elutruult'),
 ('manner', 'emergentselt'),
 ('manner', 'empiiriliselt'),
 ('manner', 'en bloc'),
 ('manner', 'endaette'),
 ('manner', 'endamisi'),
 ('manner', 'en détail'),
 ('manner', 'en détail'),
 ('manner', 'endiselt'),
 ('manner', 'endist viisi'),
 ('manner', 'endistviisi'),
 ('manner', 'enesekriitiliselt'),
 ('manner', 'en gros'),
 ('manner', 'ennakult'),
 ('manner', 'ennatult'),
 ('manner', 'ennekuulmatult'),
 ('manner', 'eo ipso'),
 ('manner', 'e-postitsi'),
 ('manner', 'erakordselt'),
 ('manner', 'erakorraliselt'),
 ('manner', 'eraldatult'),
 ('manner', 'erateel'),
 ('manner', 'eraviisil'),
 ('manner', 'eredalt'),
 ('manner', 'eredasti'),
 ('manner', 'ergalt'),
 ('manner', 'ergemalt'),
 ('manner', 'ergimalt'),
 ('manner', 'ergult'),
 ('manner', 'ergumalt'),
 ('manner', 'eriaegselt'),
 ('manner', 'erinevalt'),
 ('manner', 'erisuguselt'),
 ('manner', 'erksalt'),
 ('manner', 'erksamalt'),
 ('manner', 'erksamini'),
 ('manner', 'eroico'),
 ('manner', 'erudeeritult'),
 ('manner', 'espressivo'),
 ('manner', 'essusti'),
 ('manner', 'etapi kaupa'),
 ('manner', 'etapikaupa'),
 ('manner', 'etapiti'),
 ('manner', 'etapi viisi'),
 ('manner', 'etapiviisi'),
 ('manner', 'ettearvatult'),
 ('manner', 'ettekavatsetult'),
 ('manner', 'ettevaatlikult'),
 ('manner', 'eufooriliselt'),
 ('manner', 'ex officio'),
 ('manner', 'faktiliselt'),
 ('manner', 'feroce'),
 ('manner', 'festivo'),
 ('manner', 'fifty-sixty'),
 ('manner', 'filisterlikult'),
 ('manner', 'flebile'),
 ('manner', 'formaaljuriidiliselt'),
 ('manner', 'formaalselt'),
 ('manner', 'fugato'),
 ('manner', 'furioso'),
 ('manner', 'giocoso'),
 ('manner', 'giusto'),
 ('manner', 'grandioso'),
 ('manner', 'grazioso'),
 ('manner', 'grupiti'),
 ('manner', 'grupi viisi'),
 ('manner', 'grupiviisi'),
 ('manner', 'haigelt'),
 ('manner', 'hajutatult'),
 ('manner', 'hakitult'),
 ('manner', 'halastamatult'),
 ('manner', 'halduskorras'),
 ('manner', 'haledalt'),
 ('manner', 'haledasti'),
 ('manner', 'hallilt'),
 ('manner', 'halvatult'),
 ('manner', 'halvavalt'),
 ('manner', 'halvustavalt'),
 ('manner', 'hammustavalt'),
 ('manner', 'hapralt'),
 ('manner', 'haprasti'),
 ('manner', 'hapult'),
 ('manner', 'harali'),
 ('manner', 'hardalt'),
 ('manner', 'hardasti'),
 ('manner', 'hardunult'),
 ('manner', 'harilikult'),
 ('manner', 'harjapidi'),
 ('manner', 'harjunult'),
 ('manner', 'harkis jalu'),
 ('manner', 'harkisjalu'),
 ('manner', 'haruharva'),
 ('manner', 'harukordadel'),
 ('manner', 'harukordselt'),
 ('manner', 'harukorral'),
 ('manner', 'harukorril'),
 ('manner', 'harutihti'),
 ('manner', 'harvem'),
 ('manner', 'harvemini'),
 ('manner', 'heameelega'),
 ('manner', 'heast-paremast'),
 ('manner', 'heas usus'),
 ('manner', 'heitunult'),
 ('manner', 'heldinult'),
 ('manner', 'heledalt'),
 ('manner', 'heledasti'),
 ('manner', 'hellalt'),
 ('manner', 'hellasti'),
 ('manner', 'hergelt'),
 ('manner', 'hetkeliselt'),
 ('manner', 'hetkelt'),
 ('manner', 'higiselt'),
 ('manner', 'hiilimisi'),
 ('manner', 'hiilivalt'),
 ('manner', 'hiirvagusi'),
 ('manner', 'hilinenult'),
 ('manner', 'hilissügiseselt'),
 ('manner', 'hilju'),
 ('manner', 'hiljukesi'),
 ('manner', 'himuti'),
 ('manner', 'himutsevalt'),
 ('manner', 'hindavalt'),
 ('manner', 'hingestatult'),
 ('manner', 'hingpakki'),
 ('manner', 'hingpakkis'),
 ('manner', 'hingpuhult'),
 ('manner', 'hirmunult'),
 ('manner', 'hitchcockilikult'),
 ('manner', 'hoiatavalt'),
 ('manner', 'hoide'),
 ('manner', 'holpsti'),
 ('manner', 'hoobilt'),
 ('manner', 'hoogsalt'),
 ('manner', 'hoogsasti'),
 ('manner', 'hoo kaupa'),
 ('manner', 'hookaupa'),
 ('manner', 'hoolega'),
 ('manner', 'hoolikalt'),
 ('manner', 'hoolimatult'),
 ('manner', 'hoolitsevalt'),
 ('manner', 'hoolsalt'),
 ('manner', 'hoolsamini'),
 ('manner', 'hoolsasti'),
 ('manner', 'hoopsalt'),
 ('manner', 'hoopsasti'),
 ('manner', 'hukutavalt'),
 ('manner', 'hulga kaupa'),
 ('manner', 'hulgakaupa'),
 ('manner', 'hulgakesi'),
 ('manner', 'hulgemini'),
 ('manner', 'hulgiti'),
 ('manner', 'huupi'),
 ('manner', 'huvitavalt'),
 ('manner', 'huvitult'),
 ('manner', 'hõlma pidi'),
 ('manner', 'hõlmapidi'),
 ('manner', 'hõlpsamini'),
 ('manner', 'hõredalt'),
 ('manner', 'hõredamini'),
 ('manner', 'hõredasti'),
 ('manner', 'häbenemisi'),
 ('manner', 'hädaga'),
 ('manner', 'hädamisi'),
 ('manner', 'hädapärast'),
 ('manner', 'hädavaevalt'),
 ('manner', 'hädavaevu'),
 ('manner', 'häirimatult'),
 ('manner', 'häiritult'),
 ('manner', 'häirivalt'),
 ('manner', 'hämmastavalt'),
 ('manner', 'hämmastunult'),
 ('manner', 'hämmeldunult'),
 ('manner', 'härdalt'),
 ('manner', 'härdasti'),
 ('manner', 'härgamisi'),
 ('manner', 'hävimatult'),
 ('manner', 'hävitavalt'),
 ('manner', 'häälekalt'),
 ('manner', 'hüljatult'),
 ('manner', 'hüperaktiivselt'),
 ('manner', 'hüplikult'),
 ('manner', 'ideaaljuhul'),
 ('manner', 'ideaalselt'),
 ('manner', 'ideeliselt'),
 ('manner', 'idiootlikult'),
 ('manner', 'igakülgselt'),
 ('manner', 'iga naks'),
 ('manner', 'iga pidi'),
 ('manner', 'igapidi'),
 ('manner', 'igatekanti'),
 ('manner', 'igatemoodi'),
 ('manner', 'igatepidi'),
 ('manner', 'igateviisi'),
 ('manner', 'igati'),
 ('manner', 'igatipidi'),
 ('manner', 'igat pidi'),
 ('manner', 'igatpidi'),
 ('manner', 'igatsevalt'),
 ('manner', 'igatviisi'),
 ('manner', 'igavlevalt'),
 ('manner', 'iiliti'),
 ('manner', 'ilkuvalt'),
 ('manner', 'illustratiivselt'),
 ('manner', 'ilmaaegu'),
 ('manner', 'ilmaasjata'),
 ('manner', 'ilmekalt'),
 ('manner', 'ilmselgelt'),
 ('manner', 'ilmtingimata'),
 ('manner', 'ilusalt'),
 ('manner', 'ilusasti'),
 ('manner', 'ilusti'),
 ('manner', 'imekiiresti'),
 ('manner', 'imekombel'),
 ('manner', 'imekähku'),
 ('manner', 'imeruttu'),
 ('manner', 'imestamisi'),
 ('manner', 'imestunult'),
 ('manner', 'imeväel'),
 ('manner', 'incognito'),
 ('manner', 'in corpore'),
 ('manner', 'indiviiditi'),
 ('manner', 'inertselt'),
 ('manner', 'in flagranti'),
 ('manner', 'inglikeeli'),
 ('manner', 'inimeseti'),
 ('manner', 'inimesiti'),
 ('manner', 'inkognito'),
 ('manner', 'innukalt'),
 ('manner', 'in spe'),
 ('manner', 'instinktiivselt'),
 ('manner', 'internatsionaalselt'),
 ('manner', 'intuitiivselt'),
 ('manner', 'in vitro'),
 ('manner', 'in vivo'),
 ('manner', 'irevil'),
 ('manner', 'irevile'),
 ('manner', 'irvi'),
 ('manner', 'irvis'),
 ('manner', 'irvisui'),
 ('manner', 'isalikult'),
 ('manner', 'isekeskis'),
 ('manner', 'isepäi'),
 ('manner', 'isetahtsi'),
 ('manner', 'iseviisi'),
 ('manner', 'isiklikult'),
 ('manner', 'isikuti'),
 ('manner', 'isukalt'),
 ('manner', 'isutult'),
 ('manner', 'itsis'),
 ('manner', 'jadamisi'),
 ('manner', 'jae'),
 ('manner', 'jagamatult'),
 ('manner', 'jahvatatult'),
 ('manner', 'jala'),
 ('manner', 'jalga pidi'),
 ('manner', 'jalgapidi'),
 ('manner', 'jalg-jalalt'),
 ('manner', 'jalgsi'),
 ('manner', 'jalgu pidi'),
 ('manner', 'jalgupidi'),
 ('manner', 'jaluli'),
 ('manner', 'jamasti'),
 ('manner', 'jaopärast'),
 ('manner', 'jonksti'),
 ('manner', 'joobnud päi'),
 ('manner', 'joobnudpäi'),
 ('manner', 'joobnult'),
 ('manner', 'jooksujalu'),
 ('manner', 'jooksult'),
 ('manner', 'jooksupealt'),
 ('manner', 'joondu'),
 ('manner', 'juhtumisi'),
 ('manner', 'juhuslikult'),
 ('manner', 'juhuti'),
 ('manner', 'julmalt'),
 ('manner', 'jumalakartlikult'),
 ('manner', 'jumalakeeli'),
 ('manner', 'jumalamuidu'),
 ('manner', 'jumekalt'),
 ('manner', 'jumetult'),
 ('manner', 'jupi kaupa'),
 ('manner', 'jupikaupa'),
 ('manner', 'jupiti'),
 ('manner', 'jupphaaval'),
 ('manner', 'jutilt'),
 ('manner', 'jutis'),
 ('manner', 'juttis'),
 ('manner', 'juulikuiselt'),
 ('manner', 'jõngalt'),
 ('manner', 'jõngilt'),
 ('manner', 'jõnkadi-jõnkadi'),

### Add semantic types to lemmas in the database

In [8]:
def semtype_to_db(table_name, semtypes, cursor, conn):
    # Step 1: add new column to database table
    if not column_exists(cursor, table_name, "ekilex_tag"):
        cursor.execute("ALTER TABLE " + table_name + " ADD COLUMN ekilex_tag TEXT")

    # Step 2: add word + semantic tag to temporary table
    cursor.execute("CREATE TEMP TABLE IF NOT EXISTS temp_updates (lemma TEXT PRIMARY KEY, ekilex_tag TEXT)")
    cursor.executemany("INSERT INTO temp_updates (ekilex_tag, lemma) VALUES (?, ?)", semtypes)

    # Step 3: Add temporary table info to database table
    #ps, pronouns are excluded for spatial obliques
    cursor.execute(f"""
        UPDATE {table_name}
        SET ekilex_tag = (SELECT ekilex_tag FROM temp_updates WHERE temp_updates.lemma = {table_name}.lemma)
        WHERE pos != 'P' AND EXISTS (SELECT 1 FROM temp_updates WHERE temp_updates.lemma = {table_name}.lemma)
    """)

    conn.commit()
    conn.close()

In [9]:
semtype_to_db('spatial_obl', word_semtype_obl, cursor_db, conn_db)

In [11]:
semtype_to_db('advmod', word_semtype_adv, cursor_db, conn_db)

In [12]:
conn_db.close()

## juurde lisatud ner&timex jaoks

## Add NER & TIMEX

In [13]:
import pandas as pd

In [14]:
# connecting with database
conn = sqlite3.connect(NER_TIMEX_DB)
cursor = conn.cursor()

In [15]:
# get ner and timex tables
query = f"SELECT * FROM ner"
ner = pd.read_sql(query, conn)

query = f"SELECT * FROM timex"
timex = pd.read_sql(query, conn)

In [16]:
conn.close()

In [21]:
# add ner and timex to the other db file

# connecting with database
conn = sqlite3.connect(DATABASE)
cursor = conn.cursor()

In [18]:
ner.to_sql("ner", conn, if_exists="replace", index=False)
timex.to_sql("timex", conn, if_exists="replace", index=False)

2179320

## Update spatial_obl table

In [19]:
if not column_exists(cursor, "spatial_obl", "ner_tag"):
    cursor.execute("ALTER TABLE " + "spatial_obl" +  " ADD COLUMN ner_tag TEXT")

In [20]:
# Update `table1.x` with values from `table2.x`
cursor.execute("""
        UPDATE spatial_obl
        SET ner_tag = ner.ner_tag
        FROM ner
        WHERE spatial_obl.sentence_id = ner.sentence_id and spatial_obl.row_loc=ner.loc;
    """)

conn.commit()
conn.close()

In [22]:
if not column_exists(cursor, "spatial_obl", "timex_tag"):
    cursor.execute("ALTER TABLE " + "spatial_obl" +  " ADD COLUMN timex_tag TEXT")

In [23]:
# Update `table1.x` with values from `table2.x`
cursor.execute("""
        UPDATE spatial_obl
        SET timex_tag = timex.timex_type
        FROM timex
        WHERE spatial_obl.sentence_id = timex.sentence_id and spatial_obl.row_loc=timex.loc;
    """)

conn.commit()
conn.close()

In [24]:
# kontroll
# connecting with database
conn = sqlite3.connect(DB2)
cursor = conn.cursor()

In [25]:
query = f"SELECT * FROM spatial_obl where ner_tag is not null limit 10"

res = pd.read_sql(query, conn)
res

,id,head_id,form,lemma,feats,pos,verb,verb_compound,sentence_id,row_loc,sentence,ekilex_tag,ner_tag,timex_tag
0,444,282,Pariisis,Pariis,"in,prop,sg",S,külastama,,160,5,"Vahepeal , maikuus külastasin Pariisis veel Ol...",location,LOC,None
1,773,481,linnal,linn,"ad,com,sg",S,tulema,,259,30,Aivar Mäe arvab aasta tegu ehk Pärnu Kontserdi...,None,LOC,None
2,1017,613,Eestis,Eesti,"in,prop,sg",S,väärima,,333,1,Eestis väärib oma tiitlit Erki Nool .,location,LOC,None
3,1586,953,Robbie'le,Robbie,"all,prop,sg",S,meeldima,,525,3,Kuuldavasti meeldib Robbie'le ka kihla vedada ...,None,PER,None
4,1743,1026,Tiinale,Tiina,"all,prop,sg",S,loovutama,,578,4,Lahutades loovutas viimane Tiinale aktsiaid ni...,None,PER,None
5,1807,1055,Tallinnas,Tallinn,"in,prop,sg",S,kandideerima,,597,5,1999. aastal kandideeris ta Tallinnas kohalike...,location,LOC,None
6,1838,1069,Neiveltil,Neivelt,"ad,prop,sg",S,soovitama,,605,4,"Tiina Mõis soovitas Neiveltil , keda ta ise on...",None,LOC,None
7,1866,1085,Otepäält,Otepää,"abl,prop,sg",S,kolima,,614,14,Kui Tiina vanem õde Maie koos olümpiavõitjast ...,location,LOC,None
8,1867,1085,Tallinnasse,Tallinn,"ill,prop,sg",S,kolima,,614,15,Kui Tiina vanem õde Maie koos olümpiavõitjast ...,location,LOC,None
9,1886,1090,koolis,kool,"com,in,sg",S,töötama,,617,7,"Jaak Uudmäe töötab Rocca al Mare koolis , mill...",None,ORG,None

In [26]:
query = f"SELECT * FROM spatial_obl where timex_tag is not null limit 10"

res = pd.read_sql(query, conn)
res

,id,head_id,form,lemma,feats,pos,verb,verb_compound,sentence_id,row_loc,sentence,ekilex_tag,ner_tag,timex_tag
0,1,2,lõpus,lõpp,"com,in,sg",S,toimuma,,3,3,Kaheksakümnendate aastate lõpus toimus Türi 1.,None,None,DATE
1,129,84,ajal,aeg,"ad,com,sg",S,loobuma,,54,3,Olen viimasel ajal juhutöödest loobunud ja kir...,None,None,DATE
2,155,98,hommikust,hommik,"com,el,sg",S,jooma,,63,18,"Ma ei saa aru inimestest , kes üldse napsu ei ...",None,None,TIME
3,205,142,hommikust,hommik,"com,el,sg",S,helistama,,84,14,"Mõned tüdrukud muutusid lausa tüütuks , uurisi...",None,None,TIME
4,221,157,aastal,aasta,"ad,com,sg",S,täitma,,92,2,"Sel aastal täitsime oma missiooni , mille eesm...",None,None,DATE
5,281,190,kevadel,kevad,"ad,com,sg",S,kavatsema,,110,13,Mul tekkis viis aastat tagasi tõsine huvi lenn...,time,None,DATE
6,346,231,oktoobris,oktoober,"com,in,sg",S,saama,,133,7,Priit : Tuttavaks saime 1998. aasta oktoobris ...,None,None,DATE
7,377,245,päeval,päev,"ad,com,sg",S,sattuma,,141,8,Aga Võitlevasse Sõnasse sattusin täiesti juhus...,None,None,DATE
8,416,271,aastal,aasta,"ad,com,sg",S,naasma,,153,11,"Olin omadega puntras , sest just enne seda , 1...",None,None,DATE
9,443,282,maikuus,maikuu,"com,in,sg",S,külastama,,160,3,"Vahepeal , maikuus külastasin Pariisis veel Ol...",None,None,DATE

In [27]:
conn.close()