In [2]:
import csv
import pandas as pd
import glob
import os
import random

In [3]:
folder = "C:\\Users\\kertu.saul\\OneDrive - Eesti Keele Instituut\\Dokumendid\\doktoritoo\\estnltk_syntax_repo_kloon\\physical_location_labelling\\physical_location_by_context\\v07_all_types_goldstandard\\base_data\\LLM_annotated_batches"
files = glob.glob(os.path.join(folder, "*.csv"))
df = pd.concat(
    [pd.read_csv(file) for file in files],
    ignore_index=True
)

In [5]:
#before removing duplicates: 515893 rows
df

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,tags,...,ekilex_tag,ner_tag,A,E,T,L1,L2,L,S,tag
0,6575811,10580540,19,elama,NaN,all,edu,edule,""" Väikeseid konflikte inimeste vahel tuleb ikk...",NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
1,2836463,4549021,4,kuuluma,NaN,ill,al-Qaida,al-Qaidasse,Ülejäänud kaks meest al-Qaidasse teadaolevalt ...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
2,2131333,3403848,20,heitma,NaN,all,kuru,kurule,Sisside ja Vene sõjaväelaste lahingutega samaa...,|L|AL|EL|LS|LT|ALT|ELT|LST|,...,location,NaN,no,no,no,yes,no,yes,no,L
3,8062799,12939052,1,jätma,NaN,el,esineja,Esinejatest,Esinejatest jättis parima mulje Marek Strandbe...,|A|AE|AL|AS|AT|AET|ALT|AST|,...,alive,NaN,yes,no,no,no,no,no,no,A
4,19057361,28756967,9,jääma,puudu,ad,Kalevipoeg,Kalevipojal,Tuletaksin meelde meie rahvuseepose Kalevipoja...,|A|AE|AL|AS|AT|AET|ALT|AST|,...,alive,NaN,yes,no,no,no,no,no,no,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515888,10711639,17164924,6,surema,NaN,adit,valdus,valdusse,Frank ja Vinnie saavad oma valdusse Surnud Koe...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
515889,5235186,8398817,3,haigestuma,NaN,ill,valgusallergia,valgusallergiasse,Hannelore haigestus valgusallergiasse 1993. aa...,NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
515890,8758718,14058979,14,surema,NaN,adit,külm,külma,"Enne seda , kui emad õppisid varrastel kuduma ...",NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
515891,11717337,18752192,1,surema,NaN,adit,ving,Vingu,Vingu ja põletushaavadesse on aga surnud 64-aa...,NaN,...,NaN,NaN,no,no,no,no,no,no,yes,S
515892,6036204,9687201,7,haigestuma,NaN,adit,MM,MM-i,Nool haigestus talvel enne Birminghami sise MM...,|E|AE|EL|ET|AET|ELT|,...,event,NaN,no,yes,no,no,no,no,no,E

In [4]:
#after removing duplicates: 428973 rows
df = df.drop_duplicates(subset=['sentence_id', 'form'])

In [6]:
random.randint(1, 100000)

47509

In [7]:
df_1000 = df.sample(n=1000, random_state = 47509)
df_1000

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,tags,...,ekilex_tag,ner_tag,A,E,T,L1,L2,L,S,tag
300368,10773339,17257273,11,koonduma,NaN,adit,keskarvutis,keskarvutisse,Igale lossis olevale uksele pannakse magnetluk...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
507696,6117206,9818182,9,lõppema,NaN,el,suvi,suvest,""" Seevastu vanemates klassides lõppeb kool nii...",|T|AT|ET|LT|ST|AET|ALT|AST|ELT|LST|,...,time,NaN,no,no,yes,no,no,no,no,T
103236,6466678,10398441,12,kestma,NaN,all,tänav,tänavale,Kuna tegemist on suuremõõtmelise eriveosega ke...,|L|AL|EL|LS|LT|ALT|ELT|LST|,...,location,NaN,no,no,no,yes,no,yes,no,L
30647,2479356,3975787,14,tähistama,NaN,all,tase,tasemele,Väidetavalt olevat presidendi julgeolekunõunik...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
475473,9612010,15428229,4,laiutama,NaN,ad,sadamaala,sadamaalal,Praegu aga laiutab sadamaalal kena roheline lo...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193380,11140724,17846275,3,piisama,NaN,el,68.67,68.67-st,Avakatsel heidetud 68.67-st piisas täiesti .,NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
372222,9683051,15538849,20,edastama,NaN,ill,arvuti,arvutisse,Täna hommikupoolikul üritab maanteeamet Tallin...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
15253,1671352,2661455,15,tundma,NaN,el,isiksusepuudus,isiksusepuudusest,Umbes 50 protsenti 1200 täiskasvanud vastajast...,NaN,...,NaN,NaN,no,no,no,no,no,no,yes,S
312183,2783681,4463967,10,opereerima,NaN,ad,mai,mail,Tein opereerib koos Soome mäesuusakoondise ars...,|T|AT|ET|LT|ST|AET|ALT|AST|ELT|LST|,...,NaN,NaN,no,no,yes,no,no,no,no,T
327332,1064558,1691974,8,välistama,NaN,in,algus,alguses,Aga ma ei välista seda järgmise aasta alguses ...,|T|AT|ET|LT|ST|AET|ALT|AST|ELT|LST|,...,NaN,NaN,no,no,yes,no,no,no,no,T

In [8]:
df_1000.to_csv("LLM_sample_1000.csv", index=False, encoding="UTF-8")

## Check result csv

In [13]:
df_csv = pd.read_csv("LLM_sample_1000.csv")

In [15]:
#number of rows
len(df_csv.index)

1000

In [19]:
#check if it has duplicate rows
duplicates = df_csv[df_csv.duplicated(subset=['sentence_id', 'form'])]
duplicates

Empty DataFrame
Columns: [sentence_id, head_id, head_loc, verb, verb_compound, morph_case, lemma, form, sentence, tags, timex_tag, ekilex_tag, ner_tag, A, E, T, L1, L2, L, S, tag]
Index: []

[0 rows x 21 columns]

In [21]:
#check if all csv rows are in the original data
matching_rows = pd.merge(df, df_csv, how='inner')
matching_rows

,sentence_id,head_id,head_loc,verb,verb_compound,morph_case,lemma,form,sentence,tags,...,ekilex_tag,ner_tag,A,E,T,L1,L2,L,S,tag
0,3640597,5862887,17,ennustama,NaN,all,Forekspank,Forekspangale,Suurimat kasumikasvu - ligikaudu 90 protsenti ...,|A|AE|AL|AS|AT|AET|ALT|AST|,...,NaN,ORG,no,no,no,yes,no,yes,no,L
1,299433,470857,15,eemalduma,NaN,el,vokaal,vokaalidest,Tema kõrgenenud keskkõrgete vokaalide formantv...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
2,3278964,5270494,9,tahtma,NaN,el,jagamine,jagamisest,Eestlane teatavasti on üks individualistlik el...,NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
3,1529397,2433622,7,vähenema,NaN,all,tööjõud,tööjõule,Liiati ei vähenenud tehnika ostmisega kulutuse...,NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
4,5526954,8861755,8,tegema,NaN,el,Leigo,Leigost,Kui Soome televisioon tegi mõne aasta eest Lei...,NaN,...,NaN,NaN,no,no,no,yes,no,yes,no,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,11891858,19029970,9,minema,vastu,in,restoran,restoranis,Preester Josip Stefancic läks ööl vastu pühapä...,|L|AL|EL|LS|LT|ALT|ELT|LST|,...,organisation,NaN,no,yes,no,no,no,no,no,E
996,7256861,11669746,19,juhinduma,NaN,el,kasum,kasumist,Sarnane on olukord paljudes loodusmaastikes - ...,NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
997,8667856,13906919,1,johtuma,NaN,el,autostumine,Autostumisest,Autostumisest johtuvad probleemid,NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
998,16328793,25275418,49,surema,NaN,adit,rod,rodi,"ja seal pole yldsegi kergem , kuna need teise ...",NaN,...,NaN,NaN,no,no,no,no,no,no,no,NaN
999,591658,937651,4,põdema,NaN,adit,puukentsefaliit,puukentsefaliiti,Mullu põdes Lätis puukentsefaliiti umbes 600 i...,|S|AS|LS|ST|AST|LST|,...,state,NaN,no,no,no,no,no,no,no,NaN

### LLM tag distribution

In [23]:
df_csv.value_counts('tag', dropna=False)

tag
L      423
NaN    176
E      160
A      145
T       63
S       33
Name: count, dtype: int64

### Verb amount

In [6]:
unique_combinations = df[['verb', 'verb_compound']].drop_duplicates()
unique_combinations

              verb verb_compound
0            elama           NaN
1          kuuluma           NaN
2           heitma           NaN
3            jätma           NaN
4            jääma         puudu
...            ...           ...
510007     sündima           NaN
510021     johtuma           NaN
510034   juhinduma           NaN
510038      minema         vastu
515265  haigestuma           NaN

[1312 rows x 2 columns]

In [7]:
unique_case = df[['verb', 'verb_compound', 'morph_case']].drop_duplicates()
unique_case

              verb verb_compound morph_case
0            elama           NaN        all
1          kuuluma           NaN        ill
2           heitma           NaN        all
3            jätma           NaN         el
4            jääma         puudu         ad
...            ...           ...        ...
515261      põdema           NaN       adit
515262      surema           NaN       adit
515265  haigestuma           NaN       adit
515266    nakatuma           NaN       adit
515274  haigestuma           NaN        ill

[2232 rows x 3 columns]