## Corrections

In initially created verb pattern tables, the compound parts of longer verb constructions were separated into different columns.
Since in transactions database the compound parts are saved into the same column (as a singular string with compound parts separated by ', ' and ordered alphabetically), the representation in verb pattern tables will also be corrected by joining compound part columns.

In [1]:
import pandas as pd

## Input parameters

In [27]:
INPUT_DIR = "../source_data/rection_patterns_in_standard_format"

INPUT_FILE_LEN1 = f"{INPUT_DIR}/verb_patterns_len1_new.csv"
INPUT_FILE_LEN2 = f"{INPUT_DIR}/verb_patterns_len2_new.csv"
RESULT_FILE_LEN1 = f"{INPUT_DIR}/verb_patterns_len1_new_correct.csv"
RESULT_FILE_LEN2 = f"{INPUT_DIR}/verb_patterns_len2_new_correct.csv"

## Data processing

In [28]:
df_len1 = pd.read_csv(INPUT_FILE_LEN1)
df_len2 = pd.read_csv(INPUT_FILE_LEN2)

df_len1 = df_len1.fillna('')
df_len2 = df_len2.fillna('')

def join_and_sort_compound_prt(compound_prt_list):
    compound_prt_list = [el for el in compound_prt_list if el!='']
    sorted_lst = sorted(compound_prt_list)
    return ', '.join(sorted_lst)

def get_sorted_strings(df):
    sorted_strs = []
    for idx, row in df.iterrows():
        sorted_strs.append(join_and_sort_compound_prt([row['compound_prt1'], row['compound_prt2'], row['compound_prt3']]))       
    return sorted_strs

sorted_strs_len1 = get_sorted_strings(df_len1)
sorted_strs_len2 = get_sorted_strings(df_len2)

df_len1.insert(4, 'verb_compound', sorted_strs_len1)
df_len2.insert(4, 'verb_compound', sorted_strs_len2)

df_len1['verb_compound'] = sorted_strs_len1
df_len2['verb_compound'] = sorted_strs_len2

df_len1 = df_len1.drop(['compound_prt1', 'compound_prt2', 'compound_prt3'], axis=1)
df_len2 = df_len2.drop(['compound_prt1', 'compound_prt2', 'compound_prt3'], axis=1)

df_len1 = df_len1.drop('Unnamed: 0', axis=1)
df_len2 = df_len2.drop('Unnamed: 0', axis=1)

df_len1.to_csv(RESULT_FILE_LEN1, encoding='utf-8')
df_len2.to_csv(RESULT_FILE_LEN2, encoding='utf-8')

## Result

In [29]:
df_len1

,word,government,verb_word,verb_compound,government_with_case,case,adp,verb,other
0,aasima,keda*,aasima,,part,part,,,
1,aasima,kelle kallal,aasima,,gen kallal,gen,kallal,,
2,abielluma,kellega,abielluma,,kom,kom,,,
3,abikätt ulatama,kellele,ulatama,abikätt,all,all,,,
4,abstraheeruma,millest/kellest,abstraheeruma,,el,el,,,
...,...,...,...,...,...,...,...,...,...
2521,ümmardama,keda*,ümmardama,,part,part,,,
2522,üritama,mida teha,üritama,,part teha,part,,teha,
2523,ütlema,kellele,ütlema,,all,all,,,
2524,ütlema,kelle/mille kohta,ütlema,,gen kohta,gen,kohta,,
2525,žongleerima,millega,žongleerima,,kom,kom,,,

In [30]:
df_len2

,word,government,verb_word,verb_compound,government_with_case,member1_case,member1_adp,member1_other,member2_case,member2_adp,member2_verb,member2_other
0,abistama,keda/mida* + milles,abistama,,part + in,part,,,in,,,
1,aitama,kellel + mida teha,aitama,,ad + part teha,ad,,,part,,teha,
2,alla kirjutama,mille/mida,kirjutama,alla,part gen,part,,,gen,,,
3,ette heitma,kellele/millele + mida*,heitma,ette,all + part,all,,,part,,,
4,informeerima,keda* + millest,informeerima,,part + el,part,,,el,,,
5,jagama,mida* + kellega,jagama,,part + kom,part,,,kom,,,
6,kaasa lööma,milles/kus,lööma,kaasa,in ad,in,,,ad,,,
7,kaasa tegema,milles/kus,tegema,kaasa,in ad,in,,,ad,,,
8,kannatama,mille all,kannatama,,gen all,gen,,,all,,,
9,keelama,kellel + mida teha,keelama,,ad + part teha,ad,,,part,,teha,
10,kleepima,millele + mille peale,kleepima,,all + gen peale,all,,,gen,peale,,
11,kohtlema,keda/mida* + kuidas,kohtlema,,part + kuidas,part,,,,,,kuidas
12,kokku leppima,kellega + milles,leppima,kokku,kom + in,kom,,,in,,,
13,käskima,kellel + mida teha,käskima,,ad + part teha,ad,,,part,,teha,
14,kõrvale jääma,millest/kust,jääma,kõrvale,abl el,abl,,,el,,,
15,küsima,kellelt + mida*,küsima,,abl + part,abl,,,part,,,
16,küsima,kelle käest + mida*,küsima,,gen käest + part,gen,käest,,part,,,
17,laskma,kellel + mida teha,laskma,,ad + part teha,ad,,,part,,teha,
18,lubama,kellel + mida teha,lubama,,ad + part teha,ad,,,part,,teha,
19,läbi rääkima,kellega + mille suhtes,rääkima,läbi,kom + gen suhtes,kom,,,gen,suhtes,,
20,mugandama,millele/millega,mugandama,,kom all,kom,,,all,,,
21,nappima,kellel + milleks,nappima,,ad + tr,ad,,,tr,,,
22,nimetama,keda/mida kelleks/milleks,nimetama,,part tr,part,,,tr,,,
23,näima,milline/millisena,näima,,nom es,nom,,,es,,,
24,ostma,mille/mida,ostma,,part gen,part,,,gen,,,
25,paluma,kellel + mida teha,paluma,,ad + part teha,ad,,,part,,teha,
26,pidama,keda* + kelleks,pidama,,part + tr,part,,,tr,,,
27,piisama,kellele + millest,piisama,,all + el,all,,,el,,,
28,soovima,kellele + mida*,soovima,,all + part,all,,,part,,,
29,soovitama,kellel + mida teha,soovitama,,ad + part teha,ad,,,part,,teha,
30,sundima,keda + mida tegema,sundima,,part + part tegema,part,,,part,,tegema,
31,takistama,kellel + mida teha,takistama,,ad + part teha,ad,,,part,,teha,
32,teada saama,millest/mille kohta,saama,teada,el gen kohta,el,,,gen,kohta,,
33,teavitama,keda + millest,teavitama,,part + el,part,,,el,,,
34,tooma,kuhu + millega,tooma,,all + kom,all,,,kom,,,
35,tooma,kust + kuhu,tooma,,abl + all,abl,,,all,,,
36,tulema,kellel + mida teha,tulema,,ad + part teha,ad,,,part,,teha,
37,tunduma,milline + millisena,tunduma,,nom + es,nom,,,es,,,
38,täiendama,mida* + millega,täiendama,,part + kom,part,,,kom,,,
39,tõlkima,mis keelest + mis keelde,tõlkima,,nom keelest + nom keelde,nom,,keelest,nom,,,keelde
40,vedama,kuhu + millega,vedama,,all + kom,all,,,kom,,,
41,viima,kust + kuhu,viima,,abl + all,abl,,,all,,,
42,võimaldama,kellel + mida teha,võimaldama,,ad + part teha,ad,,,part,,teha,
43,ära harjutama,kellel mida,harjutama,ära,ad part,ad,,,part,,,
44,ära harjutama,keda millest,harjutama,ära,part el,part,,,el,,,